package testapp

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/italypaleale/francis/host/remote"
)

const shutdownTimeout = 15 * time.Second

// Config contains the Kubernetes-provided settings shared by the E2E applications
type Config struct {
	PodName            string
	PodIP              string
	RuntimeAddresses   []string
	BootstrapTokenFile string
	BootstrapPSK       string
	CAPEM              []byte
	HTTPAddress        string
	PeerPort           int
}

// LoadConfig reads and validates the environment injected by the E2E Kubernetes resources
func LoadConfig() (Config, error) {
	podName, err := requiredEnv("POD_NAME")
	if err != nil {
		return Config{}, err
	}
	podIP, err := requiredEnv("POD_IP")
	if err != nil {
		return Config{}, err
	}
	runtimeAddressValue, err := requiredEnv("FRANCIS_RUNTIME_ADDRESSES")
	if err != nil {
		return Config{}, err
	}
	caFile, err := requiredEnv("FRANCIS_CA_FILE")
	if err != nil {
		return Config{}, err
	}

	// Require exactly one host credential so a test cannot silently exercise the wrong bootstrap path
	bootstrapToken := strings.TrimSpace(os.Getenv("FRANCIS_BOOTSTRAP_TOKEN_FILE"))
	bootstrapPSK := os.Getenv("FRANCIS_BOOTSTRAP_PSK")
	hasBootstrapToken := bootstrapToken != ""
	hasBootstrapPSK := bootstrapPSK != ""
	if hasBootstrapToken == hasBootstrapPSK {
		return Config{}, errors.New("exactly one of FRANCIS_BOOTSTRAP_TOKEN_FILE or FRANCIS_BOOTSTRAP_PSK is required")
	}

	// Parse every runtime address so failover can use all chart replicas
	runtimeAddresses := make([]string, 0)
	for address := range strings.SplitSeq(runtimeAddressValue, ",") {
		address = strings.TrimSpace(address)
		if address != "" {
			runtimeAddresses = append(runtimeAddresses, address)
		}
	}
	if len(runtimeAddresses) == 0 {
		return Config{}, errors.New("FRANCIS_RUNTIME_ADDRESSES must contain at least one address")
	}

	// Load the CA generated by the chart runtime so every app authenticates the runtime before joining
	caPEM, err := os.ReadFile(caFile)
	if err != nil {
		return Config{}, fmt.Errorf("failed to read FRANCIS_CA_FILE: %w", err)
	}

	// Resolve the bind settings with stable defaults shared by the Kubernetes manifests
	httpAddress := os.Getenv("HTTP_ADDRESS")
	if httpAddress == "" {
		httpAddress = ":8080"
	}
	peerPort := 7571
	peerPortValue := os.Getenv("PEER_PORT")
	if peerPortValue != "" {
		peerPort, err = strconv.Atoi(peerPortValue)
		if err != nil || peerPort < 1 || peerPort > 65535 {
			return Config{}, fmt.Errorf("PEER_PORT must be a valid port, got %q", peerPortValue)
		}
	}

	return Config{
		PodName:            podName,
		PodIP:              podIP,
		RuntimeAddresses:   runtimeAddresses,
		BootstrapTokenFile: bootstrapToken,
		BootstrapPSK:       bootstrapPSK,
		CAPEM:              caPEM,
		HTTPAddress:        httpAddress,
		PeerPort:           peerPort,
	}, nil
}

// HostOptions configures a remote host to use the chart runtime and selected bootstrap credential
func (c Config) HostOptions(logger *slog.Logger) []remote.HostOption {
	// Build the transport and trust options shared by JWT and PSK bootstrap
	peerAddress := net.JoinHostPort(c.PodIP, strconv.Itoa(c.PeerPort))
	options := []remote.HostOption{
		remote.WithAddress(peerAddress),
		remote.WithBindAddress("0.0.0.0"),
		remote.WithBindPort(c.PeerPort),
		remote.WithRuntimeAddresses(c.RuntimeAddresses...),
		remote.WithPinnedCA(c.CAPEM),
		remote.WithLogger(logger),
		remote.WithShutdownGracePeriod(5 * time.Second),
	}

	// Configure the one credential LoadConfig accepted from the Kubernetes Deployment
	if c.BootstrapPSK != "" {
		options = append(options, remote.WithHostBootstrapPSK([]byte(c.BootstrapPSK)))
	} else {
		options = append(options, remote.WithHostBootstrapJWTFile(c.BootstrapTokenFile))
	}

	return options
}

// Run starts the actor host first and only exposes HTTP after the host has joined the runtime
func Run(parentCtx context.Context, host *remote.Host, handler http.Handler, address string) error {
	ctx, cancel := context.WithCancel(parentCtx)
	defer cancel()

	// Join the Francis cluster before Kubernetes can mark the application ready
	hostErrCh := make(chan error, 1)
	go func() {
		hostErrCh <- host.Run(ctx)
	}()
	select {
	case <-host.Ready():
	case err := <-hostErrCh:
		return fmt.Errorf("actor host exited during startup: %w", err)
	case <-ctx.Done():
		return nil
	}

	// Serve the public test API once actor operations can reach the runtime
	server := &http.Server{
		Addr:              address,
		Handler:           handler,
		ReadHeaderTimeout: 5 * time.Second,
	}
	srvErrCh := make(chan error, 1)
	go func() {
		srvErrCh <- server.ListenAndServe()
	}()

	// Stop both services when either one exits so Kubernetes gets an unambiguous process result
	var (
		serviceErr error
		hostErr    error
		serverErr  error
	)
	hostStopped := false
	serverStopped := false
	select {
	case <-ctx.Done():
	case hostErr = <-hostErrCh:
		hostStopped = true
		serviceErr = errors.New("actor host stopped unexpectedly")
	case serverErr = <-srvErrCh:
		serverStopped = true
		serviceErr = errors.New("HTTP server stopped unexpectedly")
	}
	cancel()

	// Drain the HTTP server so an in-flight assertion can finish cleanly
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), shutdownTimeout)
	shutdownErr := server.Shutdown(shutdownCtx)
	shutdownCancel()
	if errors.Is(shutdownErr, http.ErrServerClosed) {
		shutdownErr = nil
	}

	// Collect both service results without allowing a stuck shutdown to wedge the pod
	if !serverStopped {
		select {
		case serverErr = <-srvErrCh:
		case <-time.After(shutdownTimeout):
			serverErr = errors.New("HTTP server did not stop before the shutdown timeout")
		}
	}
	if !hostStopped {
		select {
		case hostErr = <-hostErrCh:
		case <-time.After(shutdownTimeout):
			hostErr = errors.New("actor host did not stop before the shutdown timeout")
		}
	}
	if errors.Is(serverErr, http.ErrServerClosed) {
		serverErr = nil
	}
	if errors.Is(hostErr, context.Canceled) {
		hostErr = nil
	}

	return errors.Join(serviceErr, shutdownErr, serverErr, hostErr)
}

func requiredEnv(name string) (string, error) {
	value := strings.TrimSpace(os.Getenv(name))
	if value == "" {
		return "", fmt.Errorf("%s is required", name)
	}
	return value, nil
}
