//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package components_mocks

import (
	"context"
	"io"
	"time"

	"github.com/italypaleale/francis/components"
	"github.com/italypaleale/francis/internal/ref"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActorProvider creates a new instance of MockActorProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorProvider {
	mock := &MockActorProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorProvider is an autogenerated mock type for the ActorProvider type
type MockActorProvider struct {
	mock.Mock
}

type MockActorProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorProvider) EXPECT() *MockActorProvider_Expecter {
	return &MockActorProvider_Expecter{mock: &_m.Mock}
}

// AcquireExclusiveLease provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) AcquireExclusiveLease(ctx context.Context, owner string, ttl time.Duration) (time.Time, error) {
	ret := _mock.Called(ctx, owner, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AcquireExclusiveLease")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (time.Time, error)); ok {
		return returnFunc(ctx, owner, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) time.Time); ok {
		r0 = returnFunc(ctx, owner, ttl)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, owner, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_AcquireExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireExclusiveLease'
type MockActorProvider_AcquireExclusiveLease_Call struct {
	*mock.Call
}

// AcquireExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - ttl time.Duration
func (_e *MockActorProvider_Expecter) AcquireExclusiveLease(ctx any, owner any, ttl any) *MockActorProvider_AcquireExclusiveLease_Call {
	return &MockActorProvider_AcquireExclusiveLease_Call{Call: _e.mock.On("AcquireExclusiveLease", ctx, owner, ttl)}
}

func (_c *MockActorProvider_AcquireExclusiveLease_Call) Run(run func(ctx context.Context, owner string, ttl time.Duration)) *MockActorProvider_AcquireExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_AcquireExclusiveLease_Call) Return(expiresAt time.Time, err error) *MockActorProvider_AcquireExclusiveLease_Call {
	_c.Call.Return(expiresAt, err)
	return _c
}

func (_c *MockActorProvider_AcquireExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string, ttl time.Duration) (time.Time, error)) *MockActorProvider_AcquireExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// Backup provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) Backup(ctx context.Context, w io.Writer) error {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer) error); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type MockActorProvider_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
func (_e *MockActorProvider_Expecter) Backup(ctx any, w any) *MockActorProvider_Backup_Call {
	return &MockActorProvider_Backup_Call{Call: _e.mock.On("Backup", ctx, w)}
}

func (_c *MockActorProvider_Backup_Call) Run(run func(ctx context.Context, w io.Writer)) *MockActorProvider_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_Backup_Call) Return(err error) *MockActorProvider_Backup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_Backup_Call) RunAndReturn(run func(ctx context.Context, w io.Writer) error) *MockActorProvider_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// CancelJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) CancelJob(ctx context.Context, actorType string, actorID string, jobID string) error {
	ret := _mock.Called(ctx, actorType, actorID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockActorProvider_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - jobID string
func (_e *MockActorProvider_Expecter) CancelJob(ctx any, actorType any, actorID any, jobID any) *MockActorProvider_CancelJob_Call {
	return &MockActorProvider_CancelJob_Call{Call: _e.mock.On("CancelJob", ctx, actorType, actorID, jobID)}
}

func (_c *MockActorProvider_CancelJob_Call) Run(run func(ctx context.Context, actorType string, actorID string, jobID string)) *MockActorProvider_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActorProvider_CancelJob_Call) Return(err error) *MockActorProvider_CancelJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_CancelJob_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, jobID string) error) *MockActorProvider_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeadLetterAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DeadLetterAlarm(ctx context.Context, lease *ref.AlarmLease, req components.DeadLetterAlarmReq) error {
	ret := _mock.Called(ctx, lease, req)

	if len(ret) == 0 {
		panic("no return value specified for DeadLetterAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease, components.DeadLetterAlarmReq) error); ok {
		r0 = returnFunc(ctx, lease, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_DeadLetterAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeadLetterAlarm'
type MockActorProvider_DeadLetterAlarm_Call struct {
	*mock.Call
}

// DeadLetterAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - lease *ref.AlarmLease
//   - req components.DeadLetterAlarmReq
func (_e *MockActorProvider_Expecter) DeadLetterAlarm(ctx any, lease any, req any) *MockActorProvider_DeadLetterAlarm_Call {
	return &MockActorProvider_DeadLetterAlarm_Call{Call: _e.mock.On("DeadLetterAlarm", ctx, lease, req)}
}

func (_c *MockActorProvider_DeadLetterAlarm_Call) Run(run func(ctx context.Context, lease *ref.AlarmLease, req components.DeadLetterAlarmReq)) *MockActorProvider_DeadLetterAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ref.AlarmLease
		if args[1] != nil {
			arg1 = args[1].(*ref.AlarmLease)
		}
		var arg2 components.DeadLetterAlarmReq
		if args[2] != nil {
			arg2 = args[2].(components.DeadLetterAlarmReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_DeadLetterAlarm_Call) Return(err error) *MockActorProvider_DeadLetterAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_DeadLetterAlarm_Call) RunAndReturn(run func(ctx context.Context, lease *ref.AlarmLease, req components.DeadLetterAlarmReq) error) *MockActorProvider_DeadLetterAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DeleteAlarm(ctx context.Context, ref1 ref.AlarmRef) error {
	ret := _mock.Called(ctx, ref1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef) error); ok {
		r0 = returnFunc(ctx, ref1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_DeleteAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlarm'
type MockActorProvider_DeleteAlarm_Call struct {
	*mock.Call
}

// DeleteAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.AlarmRef
func (_e *MockActorProvider_Expecter) DeleteAlarm(ctx any, ref1 any) *MockActorProvider_DeleteAlarm_Call {
	return &MockActorProvider_DeleteAlarm_Call{Call: _e.mock.On("DeleteAlarm", ctx, ref1)}
}

func (_c *MockActorProvider_DeleteAlarm_Call) Run(run func(ctx context.Context, ref1 ref.AlarmRef)) *MockActorProvider_DeleteAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.AlarmRef
		if args[1] != nil {
			arg1 = args[1].(ref.AlarmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_DeleteAlarm_Call) Return(err error) *MockActorProvider_DeleteAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_DeleteAlarm_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.AlarmRef) error) *MockActorProvider_DeleteAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeadJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DeleteDeadJob(ctx context.Context, jobID string) error {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeadJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_DeleteDeadJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeadJob'
type MockActorProvider_DeleteDeadJob_Call struct {
	*mock.Call
}

// DeleteDeadJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockActorProvider_Expecter) DeleteDeadJob(ctx any, jobID any) *MockActorProvider_DeleteDeadJob_Call {
	return &MockActorProvider_DeleteDeadJob_Call{Call: _e.mock.On("DeleteDeadJob", ctx, jobID)}
}

func (_c *MockActorProvider_DeleteDeadJob_Call) Run(run func(ctx context.Context, jobID string)) *MockActorProvider_DeleteDeadJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_DeleteDeadJob_Call) Return(err error) *MockActorProvider_DeleteDeadJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_DeleteDeadJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) error) *MockActorProvider_DeleteDeadJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLeasedAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DeleteLeasedAlarm(ctx context.Context, lease *ref.AlarmLease) error {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLeasedAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease) error); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_DeleteLeasedAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLeasedAlarm'
type MockActorProvider_DeleteLeasedAlarm_Call struct {
	*mock.Call
}

// DeleteLeasedAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - lease *ref.AlarmLease
func (_e *MockActorProvider_Expecter) DeleteLeasedAlarm(ctx any, lease any) *MockActorProvider_DeleteLeasedAlarm_Call {
	return &MockActorProvider_DeleteLeasedAlarm_Call{Call: _e.mock.On("DeleteLeasedAlarm", ctx, lease)}
}

func (_c *MockActorProvider_DeleteLeasedAlarm_Call) Run(run func(ctx context.Context, lease *ref.AlarmLease)) *MockActorProvider_DeleteLeasedAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ref.AlarmLease
		if args[1] != nil {
			arg1 = args[1].(*ref.AlarmLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_DeleteLeasedAlarm_Call) Return(err error) *MockActorProvider_DeleteLeasedAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_DeleteLeasedAlarm_Call) RunAndReturn(run func(ctx context.Context, lease *ref.AlarmLease) error) *MockActorProvider_DeleteLeasedAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteState provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DeleteState(ctx context.Context, ref1 ref.ActorRef) error {
	ret := _mock.Called(ctx, ref1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef) error); ok {
		r0 = returnFunc(ctx, ref1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_DeleteState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteState'
type MockActorProvider_DeleteState_Call struct {
	*mock.Call
}

// DeleteState is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.ActorRef
func (_e *MockActorProvider_Expecter) DeleteState(ctx any, ref1 any) *MockActorProvider_DeleteState_Call {
	return &MockActorProvider_DeleteState_Call{Call: _e.mock.On("DeleteState", ctx, ref1)}
}

func (_c *MockActorProvider_DeleteState_Call) Run(run func(ctx context.Context, ref1 ref.ActorRef)) *MockActorProvider_DeleteState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.ActorRef
		if args[1] != nil {
			arg1 = args[1].(ref.ActorRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_DeleteState_Call) Return(err error) *MockActorProvider_DeleteState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_DeleteState_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.ActorRef) error) *MockActorProvider_DeleteState_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) DispatchJob(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq) (string, error) {
	ret := _mock.Called(ctx, ref1, req)

	if len(ret) == 0 {
		panic("no return value specified for DispatchJob")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef, components.SetAlarmReq) (string, error)); ok {
		return returnFunc(ctx, ref1, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef, components.SetAlarmReq) string); ok {
		r0 = returnFunc(ctx, ref1, req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ref.AlarmRef, components.SetAlarmReq) error); ok {
		r1 = returnFunc(ctx, ref1, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_DispatchJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchJob'
type MockActorProvider_DispatchJob_Call struct {
	*mock.Call
}

// DispatchJob is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.AlarmRef
//   - req components.SetAlarmReq
func (_e *MockActorProvider_Expecter) DispatchJob(ctx any, ref1 any, req any) *MockActorProvider_DispatchJob_Call {
	return &MockActorProvider_DispatchJob_Call{Call: _e.mock.On("DispatchJob", ctx, ref1, req)}
}

func (_c *MockActorProvider_DispatchJob_Call) Run(run func(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq)) *MockActorProvider_DispatchJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.AlarmRef
		if args[1] != nil {
			arg1 = args[1].(ref.AlarmRef)
		}
		var arg2 components.SetAlarmReq
		if args[2] != nil {
			arg2 = args[2].(components.SetAlarmReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_DispatchJob_Call) Return(jobID string, err error) *MockActorProvider_DispatchJob_Call {
	_c.Call.Return(jobID, err)
	return _c
}

func (_c *MockActorProvider_DispatchJob_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq) (string, error)) *MockActorProvider_DispatchJob_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAndLeaseUpcomingAlarms provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) FetchAndLeaseUpcomingAlarms(ctx context.Context, req components.FetchAndLeaseUpcomingAlarmsReq) ([]*ref.AlarmLease, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndLeaseUpcomingAlarms")
	}

	var r0 []*ref.AlarmLease
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.FetchAndLeaseUpcomingAlarmsReq) ([]*ref.AlarmLease, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.FetchAndLeaseUpcomingAlarmsReq) []*ref.AlarmLease); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ref.AlarmLease)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.FetchAndLeaseUpcomingAlarmsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_FetchAndLeaseUpcomingAlarms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAndLeaseUpcomingAlarms'
type MockActorProvider_FetchAndLeaseUpcomingAlarms_Call struct {
	*mock.Call
}

// FetchAndLeaseUpcomingAlarms is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.FetchAndLeaseUpcomingAlarmsReq
func (_e *MockActorProvider_Expecter) FetchAndLeaseUpcomingAlarms(ctx any, req any) *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call {
	return &MockActorProvider_FetchAndLeaseUpcomingAlarms_Call{Call: _e.mock.On("FetchAndLeaseUpcomingAlarms", ctx, req)}
}

func (_c *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call) Run(run func(ctx context.Context, req components.FetchAndLeaseUpcomingAlarmsReq)) *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.FetchAndLeaseUpcomingAlarmsReq
		if args[1] != nil {
			arg1 = args[1].(components.FetchAndLeaseUpcomingAlarmsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call) Return(alarmLeases []*ref.AlarmLease, err error) *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call {
	_c.Call.Return(alarmLeases, err)
	return _c
}

func (_c *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call) RunAndReturn(run func(ctx context.Context, req components.FetchAndLeaseUpcomingAlarmsReq) ([]*ref.AlarmLease, error)) *MockActorProvider_FetchAndLeaseUpcomingAlarms_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) GetAlarm(ctx context.Context, ref1 ref.AlarmRef) (components.GetAlarmRes, error) {
	ret := _mock.Called(ctx, ref1)

	if len(ret) == 0 {
		panic("no return value specified for GetAlarm")
	}

	var r0 components.GetAlarmRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef) (components.GetAlarmRes, error)); ok {
		return returnFunc(ctx, ref1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef) components.GetAlarmRes); ok {
		r0 = returnFunc(ctx, ref1)
	} else {
		r0 = ret.Get(0).(components.GetAlarmRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ref.AlarmRef) error); ok {
		r1 = returnFunc(ctx, ref1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_GetAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlarm'
type MockActorProvider_GetAlarm_Call struct {
	*mock.Call
}

// GetAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.AlarmRef
func (_e *MockActorProvider_Expecter) GetAlarm(ctx any, ref1 any) *MockActorProvider_GetAlarm_Call {
	return &MockActorProvider_GetAlarm_Call{Call: _e.mock.On("GetAlarm", ctx, ref1)}
}

func (_c *MockActorProvider_GetAlarm_Call) Run(run func(ctx context.Context, ref1 ref.AlarmRef)) *MockActorProvider_GetAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.AlarmRef
		if args[1] != nil {
			arg1 = args[1].(ref.AlarmRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_GetAlarm_Call) Return(getAlarmRes components.GetAlarmRes, err error) *MockActorProvider_GetAlarm_Call {
	_c.Call.Return(getAlarmRes, err)
	return _c
}

func (_c *MockActorProvider_GetAlarm_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.AlarmRef) (components.GetAlarmRes, error)) *MockActorProvider_GetAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeadJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) GetDeadJob(ctx context.Context, jobID string) (components.GetDeadJobRes, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeadJob")
	}

	var r0 components.GetDeadJobRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (components.GetDeadJobRes, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) components.GetDeadJobRes); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(components.GetDeadJobRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_GetDeadJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeadJob'
type MockActorProvider_GetDeadJob_Call struct {
	*mock.Call
}

// GetDeadJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockActorProvider_Expecter) GetDeadJob(ctx any, jobID any) *MockActorProvider_GetDeadJob_Call {
	return &MockActorProvider_GetDeadJob_Call{Call: _e.mock.On("GetDeadJob", ctx, jobID)}
}

func (_c *MockActorProvider_GetDeadJob_Call) Run(run func(ctx context.Context, jobID string)) *MockActorProvider_GetDeadJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_GetDeadJob_Call) Return(getDeadJobRes components.GetDeadJobRes, err error) *MockActorProvider_GetDeadJob_Call {
	_c.Call.Return(getDeadJobRes, err)
	return _c
}

func (_c *MockActorProvider_GetDeadJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) (components.GetDeadJobRes, error)) *MockActorProvider_GetDeadJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) GetJob(ctx context.Context, jobID string) (components.JobInfo, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 components.JobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (components.JobInfo, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) components.JobInfo); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(components.JobInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockActorProvider_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockActorProvider_Expecter) GetJob(ctx any, jobID any) *MockActorProvider_GetJob_Call {
	return &MockActorProvider_GetJob_Call{Call: _e.mock.On("GetJob", ctx, jobID)}
}

func (_c *MockActorProvider_GetJob_Call) Run(run func(ctx context.Context, jobID string)) *MockActorProvider_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_GetJob_Call) Return(jobInfo components.JobInfo, err error) *MockActorProvider_GetJob_Call {
	_c.Call.Return(jobInfo, err)
	return _c
}

func (_c *MockActorProvider_GetJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) (components.JobInfo, error)) *MockActorProvider_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeasedAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) GetLeasedAlarm(ctx context.Context, lease *ref.AlarmLease) (components.GetLeasedAlarmRes, error) {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for GetLeasedAlarm")
	}

	var r0 components.GetLeasedAlarmRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease) (components.GetLeasedAlarmRes, error)); ok {
		return returnFunc(ctx, lease)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease) components.GetLeasedAlarmRes); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Get(0).(components.GetLeasedAlarmRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ref.AlarmLease) error); ok {
		r1 = returnFunc(ctx, lease)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_GetLeasedAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeasedAlarm'
type MockActorProvider_GetLeasedAlarm_Call struct {
	*mock.Call
}

// GetLeasedAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - lease *ref.AlarmLease
func (_e *MockActorProvider_Expecter) GetLeasedAlarm(ctx any, lease any) *MockActorProvider_GetLeasedAlarm_Call {
	return &MockActorProvider_GetLeasedAlarm_Call{Call: _e.mock.On("GetLeasedAlarm", ctx, lease)}
}

func (_c *MockActorProvider_GetLeasedAlarm_Call) Run(run func(ctx context.Context, lease *ref.AlarmLease)) *MockActorProvider_GetLeasedAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ref.AlarmLease
		if args[1] != nil {
			arg1 = args[1].(*ref.AlarmLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_GetLeasedAlarm_Call) Return(getLeasedAlarmRes components.GetLeasedAlarmRes, err error) *MockActorProvider_GetLeasedAlarm_Call {
	_c.Call.Return(getLeasedAlarmRes, err)
	return _c
}

func (_c *MockActorProvider_GetLeasedAlarm_Call) RunAndReturn(run func(ctx context.Context, lease *ref.AlarmLease) (components.GetLeasedAlarmRes, error)) *MockActorProvider_GetLeasedAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) GetState(ctx context.Context, ref1 ref.ActorRef) ([]byte, error) {
	ret := _mock.Called(ctx, ref1)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef) ([]byte, error)); ok {
		return returnFunc(ctx, ref1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef) []byte); ok {
		r0 = returnFunc(ctx, ref1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ref.ActorRef) error); ok {
		r1 = returnFunc(ctx, ref1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockActorProvider_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.ActorRef
func (_e *MockActorProvider_Expecter) GetState(ctx any, ref1 any) *MockActorProvider_GetState_Call {
	return &MockActorProvider_GetState_Call{Call: _e.mock.On("GetState", ctx, ref1)}
}

func (_c *MockActorProvider_GetState_Call) Run(run func(ctx context.Context, ref1 ref.ActorRef)) *MockActorProvider_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.ActorRef
		if args[1] != nil {
			arg1 = args[1].(ref.ActorRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_GetState_Call) Return(bytes []byte, err error) *MockActorProvider_GetState_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockActorProvider_GetState_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.ActorRef) ([]byte, error)) *MockActorProvider_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheckInterval provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) HealthCheckInterval() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheckInterval")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockActorProvider_HealthCheckInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheckInterval'
type MockActorProvider_HealthCheckInterval_Call struct {
	*mock.Call
}

// HealthCheckInterval is a helper method to define mock.On call
func (_e *MockActorProvider_Expecter) HealthCheckInterval() *MockActorProvider_HealthCheckInterval_Call {
	return &MockActorProvider_HealthCheckInterval_Call{Call: _e.mock.On("HealthCheckInterval")}
}

func (_c *MockActorProvider_HealthCheckInterval_Call) Run(run func()) *MockActorProvider_HealthCheckInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActorProvider_HealthCheckInterval_Call) Return(duration time.Duration) *MockActorProvider_HealthCheckInterval_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockActorProvider_HealthCheckInterval_Call) RunAndReturn(run func() time.Duration) *MockActorProvider_HealthCheckInterval_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockActorProvider_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActorProvider_Expecter) Init(ctx any) *MockActorProvider_Init_Call {
	return &MockActorProvider_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockActorProvider_Init_Call) Run(run func(ctx context.Context)) *MockActorProvider_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActorProvider_Init_Call) Return(err error) *MockActorProvider_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockActorProvider_Init_Call {
	_c.Call.Return(run)
	return _c
}

// ListHosts provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) ListHosts(ctx context.Context) ([]components.HostInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListHosts")
	}

	var r0 []components.HostInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]components.HostInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []components.HostInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.HostInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_ListHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHosts'
type MockActorProvider_ListHosts_Call struct {
	*mock.Call
}

// ListHosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActorProvider_Expecter) ListHosts(ctx any) *MockActorProvider_ListHosts_Call {
	return &MockActorProvider_ListHosts_Call{Call: _e.mock.On("ListHosts", ctx)}
}

func (_c *MockActorProvider_ListHosts_Call) Run(run func(ctx context.Context)) *MockActorProvider_ListHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActorProvider_ListHosts_Call) Return(hostInfos []components.HostInfo, err error) *MockActorProvider_ListHosts_Call {
	_c.Call.Return(hostInfos, err)
	return _c
}

func (_c *MockActorProvider_ListHosts_Call) RunAndReturn(run func(ctx context.Context) ([]components.HostInfo, error)) *MockActorProvider_ListHosts_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobs provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) ListJobs(ctx context.Context, actorType string, actorID string) ([]components.JobInfo, error) {
	ret := _mock.Called(ctx, actorType, actorID)

	if len(ret) == 0 {
		panic("no return value specified for ListJobs")
	}

	var r0 []components.JobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]components.JobInfo, error)); ok {
		return returnFunc(ctx, actorType, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []components.JobInfo); ok {
		r0 = returnFunc(ctx, actorType, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.JobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorType, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_ListJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobs'
type MockActorProvider_ListJobs_Call struct {
	*mock.Call
}

// ListJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
func (_e *MockActorProvider_Expecter) ListJobs(ctx any, actorType any, actorID any) *MockActorProvider_ListJobs_Call {
	return &MockActorProvider_ListJobs_Call{Call: _e.mock.On("ListJobs", ctx, actorType, actorID)}
}

func (_c *MockActorProvider_ListJobs_Call) Run(run func(ctx context.Context, actorType string, actorID string)) *MockActorProvider_ListJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_ListJobs_Call) Return(jobInfos []components.JobInfo, err error) *MockActorProvider_ListJobs_Call {
	_c.Call.Return(jobInfos, err)
	return _c
}

func (_c *MockActorProvider_ListJobs_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string) ([]components.JobInfo, error)) *MockActorProvider_ListJobs_Call {
	_c.Call.Return(run)
	return _c
}

// LookupActor provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) LookupActor(ctx context.Context, ref1 ref.ActorRef, opts components.LookupActorOpts) (components.LookupActorRes, error) {
	ret := _mock.Called(ctx, ref1, opts)

	if len(ret) == 0 {
		panic("no return value specified for LookupActor")
	}

	var r0 components.LookupActorRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef, components.LookupActorOpts) (components.LookupActorRes, error)); ok {
		return returnFunc(ctx, ref1, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef, components.LookupActorOpts) components.LookupActorRes); ok {
		r0 = returnFunc(ctx, ref1, opts)
	} else {
		r0 = ret.Get(0).(components.LookupActorRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ref.ActorRef, components.LookupActorOpts) error); ok {
		r1 = returnFunc(ctx, ref1, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_LookupActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupActor'
type MockActorProvider_LookupActor_Call struct {
	*mock.Call
}

// LookupActor is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.ActorRef
//   - opts components.LookupActorOpts
func (_e *MockActorProvider_Expecter) LookupActor(ctx any, ref1 any, opts any) *MockActorProvider_LookupActor_Call {
	return &MockActorProvider_LookupActor_Call{Call: _e.mock.On("LookupActor", ctx, ref1, opts)}
}

func (_c *MockActorProvider_LookupActor_Call) Run(run func(ctx context.Context, ref1 ref.ActorRef, opts components.LookupActorOpts)) *MockActorProvider_LookupActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.ActorRef
		if args[1] != nil {
			arg1 = args[1].(ref.ActorRef)
		}
		var arg2 components.LookupActorOpts
		if args[2] != nil {
			arg2 = args[2].(components.LookupActorOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_LookupActor_Call) Return(lookupActorRes components.LookupActorRes, err error) *MockActorProvider_LookupActor_Call {
	_c.Call.Return(lookupActorRes, err)
	return _c
}

func (_c *MockActorProvider_LookupActor_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.ActorRef, opts components.LookupActorOpts) (components.LookupActorRes, error)) *MockActorProvider_LookupActor_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHost provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RegisterHost(ctx context.Context, req components.RegisterHostReq) (components.RegisterHostRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHost")
	}

	var r0 components.RegisterHostRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.RegisterHostReq) (components.RegisterHostRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.RegisterHostReq) components.RegisterHostRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.RegisterHostRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.RegisterHostReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_RegisterHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHost'
type MockActorProvider_RegisterHost_Call struct {
	*mock.Call
}

// RegisterHost is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.RegisterHostReq
func (_e *MockActorProvider_Expecter) RegisterHost(ctx any, req any) *MockActorProvider_RegisterHost_Call {
	return &MockActorProvider_RegisterHost_Call{Call: _e.mock.On("RegisterHost", ctx, req)}
}

func (_c *MockActorProvider_RegisterHost_Call) Run(run func(ctx context.Context, req components.RegisterHostReq)) *MockActorProvider_RegisterHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.RegisterHostReq
		if args[1] != nil {
			arg1 = args[1].(components.RegisterHostReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_RegisterHost_Call) Return(registerHostRes components.RegisterHostRes, err error) *MockActorProvider_RegisterHost_Call {
	_c.Call.Return(registerHostRes, err)
	return _c
}

func (_c *MockActorProvider_RegisterHost_Call) RunAndReturn(run func(ctx context.Context, req components.RegisterHostReq) (components.RegisterHostRes, error)) *MockActorProvider_RegisterHost_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseAlarmLease provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) ReleaseAlarmLease(ctx context.Context, lease *ref.AlarmLease) error {
	ret := _mock.Called(ctx, lease)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseAlarmLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease) error); ok {
		r0 = returnFunc(ctx, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_ReleaseAlarmLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseAlarmLease'
type MockActorProvider_ReleaseAlarmLease_Call struct {
	*mock.Call
}

// ReleaseAlarmLease is a helper method to define mock.On call
//   - ctx context.Context
//   - lease *ref.AlarmLease
func (_e *MockActorProvider_Expecter) ReleaseAlarmLease(ctx any, lease any) *MockActorProvider_ReleaseAlarmLease_Call {
	return &MockActorProvider_ReleaseAlarmLease_Call{Call: _e.mock.On("ReleaseAlarmLease", ctx, lease)}
}

func (_c *MockActorProvider_ReleaseAlarmLease_Call) Run(run func(ctx context.Context, lease *ref.AlarmLease)) *MockActorProvider_ReleaseAlarmLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ref.AlarmLease
		if args[1] != nil {
			arg1 = args[1].(*ref.AlarmLease)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_ReleaseAlarmLease_Call) Return(err error) *MockActorProvider_ReleaseAlarmLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_ReleaseAlarmLease_Call) RunAndReturn(run func(ctx context.Context, lease *ref.AlarmLease) error) *MockActorProvider_ReleaseAlarmLease_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExclusiveLease provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) ReleaseExclusiveLease(ctx context.Context, owner string) error {
	ret := _mock.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExclusiveLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, owner)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_ReleaseExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExclusiveLease'
type MockActorProvider_ReleaseExclusiveLease_Call struct {
	*mock.Call
}

// ReleaseExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
func (_e *MockActorProvider_Expecter) ReleaseExclusiveLease(ctx any, owner any) *MockActorProvider_ReleaseExclusiveLease_Call {
	return &MockActorProvider_ReleaseExclusiveLease_Call{Call: _e.mock.On("ReleaseExclusiveLease", ctx, owner)}
}

func (_c *MockActorProvider_ReleaseExclusiveLease_Call) Run(run func(ctx context.Context, owner string)) *MockActorProvider_ReleaseExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_ReleaseExclusiveLease_Call) Return(err error) *MockActorProvider_ReleaseExclusiveLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_ReleaseExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string) error) *MockActorProvider_ReleaseExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveActor provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RemoveActor(ctx context.Context, ref1 ref.ActorRef) error {
	ret := _mock.Called(ctx, ref1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveActor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef) error); ok {
		r0 = returnFunc(ctx, ref1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_RemoveActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveActor'
type MockActorProvider_RemoveActor_Call struct {
	*mock.Call
}

// RemoveActor is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.ActorRef
func (_e *MockActorProvider_Expecter) RemoveActor(ctx any, ref1 any) *MockActorProvider_RemoveActor_Call {
	return &MockActorProvider_RemoveActor_Call{Call: _e.mock.On("RemoveActor", ctx, ref1)}
}

func (_c *MockActorProvider_RemoveActor_Call) Run(run func(ctx context.Context, ref1 ref.ActorRef)) *MockActorProvider_RemoveActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.ActorRef
		if args[1] != nil {
			arg1 = args[1].(ref.ActorRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_RemoveActor_Call) Return(err error) *MockActorProvider_RemoveActor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_RemoveActor_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.ActorRef) error) *MockActorProvider_RemoveActor_Call {
	_c.Call.Return(run)
	return _c
}

// RenewAlarmLeases provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RenewAlarmLeases(ctx context.Context, req components.RenewAlarmLeasesReq) (components.RenewAlarmLeasesRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RenewAlarmLeases")
	}

	var r0 components.RenewAlarmLeasesRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.RenewAlarmLeasesReq) (components.RenewAlarmLeasesRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.RenewAlarmLeasesReq) components.RenewAlarmLeasesRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.RenewAlarmLeasesRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.RenewAlarmLeasesReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_RenewAlarmLeases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewAlarmLeases'
type MockActorProvider_RenewAlarmLeases_Call struct {
	*mock.Call
}

// RenewAlarmLeases is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.RenewAlarmLeasesReq
func (_e *MockActorProvider_Expecter) RenewAlarmLeases(ctx any, req any) *MockActorProvider_RenewAlarmLeases_Call {
	return &MockActorProvider_RenewAlarmLeases_Call{Call: _e.mock.On("RenewAlarmLeases", ctx, req)}
}

func (_c *MockActorProvider_RenewAlarmLeases_Call) Run(run func(ctx context.Context, req components.RenewAlarmLeasesReq)) *MockActorProvider_RenewAlarmLeases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.RenewAlarmLeasesReq
		if args[1] != nil {
			arg1 = args[1].(components.RenewAlarmLeasesReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_RenewAlarmLeases_Call) Return(renewAlarmLeasesRes components.RenewAlarmLeasesRes, err error) *MockActorProvider_RenewAlarmLeases_Call {
	_c.Call.Return(renewAlarmLeasesRes, err)
	return _c
}

func (_c *MockActorProvider_RenewAlarmLeases_Call) RunAndReturn(run func(ctx context.Context, req components.RenewAlarmLeasesReq) (components.RenewAlarmLeasesRes, error)) *MockActorProvider_RenewAlarmLeases_Call {
	_c.Call.Return(run)
	return _c
}

// RenewExclusiveLease provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RenewExclusiveLease(ctx context.Context, owner string, ttl time.Duration) (time.Time, error) {
	ret := _mock.Called(ctx, owner, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RenewExclusiveLease")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (time.Time, error)); ok {
		return returnFunc(ctx, owner, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) time.Time); ok {
		r0 = returnFunc(ctx, owner, ttl)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, owner, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_RenewExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewExclusiveLease'
type MockActorProvider_RenewExclusiveLease_Call struct {
	*mock.Call
}

// RenewExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - ttl time.Duration
func (_e *MockActorProvider_Expecter) RenewExclusiveLease(ctx any, owner any, ttl any) *MockActorProvider_RenewExclusiveLease_Call {
	return &MockActorProvider_RenewExclusiveLease_Call{Call: _e.mock.On("RenewExclusiveLease", ctx, owner, ttl)}
}

func (_c *MockActorProvider_RenewExclusiveLease_Call) Run(run func(ctx context.Context, owner string, ttl time.Duration)) *MockActorProvider_RenewExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_RenewExclusiveLease_Call) Return(expiresAt time.Time, err error) *MockActorProvider_RenewExclusiveLease_Call {
	_c.Call.Return(expiresAt, err)
	return _c
}

func (_c *MockActorProvider_RenewExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string, ttl time.Duration) (time.Time, error)) *MockActorProvider_RenewExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// RenewLeaseInterval provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RenewLeaseInterval() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RenewLeaseInterval")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockActorProvider_RenewLeaseInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewLeaseInterval'
type MockActorProvider_RenewLeaseInterval_Call struct {
	*mock.Call
}

// RenewLeaseInterval is a helper method to define mock.On call
func (_e *MockActorProvider_Expecter) RenewLeaseInterval() *MockActorProvider_RenewLeaseInterval_Call {
	return &MockActorProvider_RenewLeaseInterval_Call{Call: _e.mock.On("RenewLeaseInterval")}
}

func (_c *MockActorProvider_RenewLeaseInterval_Call) Run(run func()) *MockActorProvider_RenewLeaseInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockActorProvider_RenewLeaseInterval_Call) Return(duration time.Duration) *MockActorProvider_RenewLeaseInterval_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockActorProvider_RenewLeaseInterval_Call) RunAndReturn(run func() time.Duration) *MockActorProvider_RenewLeaseInterval_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) Restore(ctx context.Context, r io.Reader) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockActorProvider_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
func (_e *MockActorProvider_Expecter) Restore(ctx any, r any) *MockActorProvider_Restore_Call {
	return &MockActorProvider_Restore_Call{Call: _e.mock.On("Restore", ctx, r)}
}

func (_c *MockActorProvider_Restore_Call) Run(run func(ctx context.Context, r io.Reader)) *MockActorProvider_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_Restore_Call) Return(err error) *MockActorProvider_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_Restore_Call) RunAndReturn(run func(ctx context.Context, r io.Reader) error) *MockActorProvider_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// RetryDeadJob provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) RetryDeadJob(ctx context.Context, jobID string) (string, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for RetryDeadJob")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorProvider_RetryDeadJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryDeadJob'
type MockActorProvider_RetryDeadJob_Call struct {
	*mock.Call
}

// RetryDeadJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockActorProvider_Expecter) RetryDeadJob(ctx any, jobID any) *MockActorProvider_RetryDeadJob_Call {
	return &MockActorProvider_RetryDeadJob_Call{Call: _e.mock.On("RetryDeadJob", ctx, jobID)}
}

func (_c *MockActorProvider_RetryDeadJob_Call) Run(run func(ctx context.Context, jobID string)) *MockActorProvider_RetryDeadJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_RetryDeadJob_Call) Return(newJobID string, err error) *MockActorProvider_RetryDeadJob_Call {
	_c.Call.Return(newJobID, err)
	return _c
}

func (_c *MockActorProvider_RetryDeadJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) (string, error)) *MockActorProvider_RetryDeadJob_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockActorProvider_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActorProvider_Expecter) Run(ctx any) *MockActorProvider_Run_Call {
	return &MockActorProvider_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockActorProvider_Run_Call) Run(run func(ctx context.Context)) *MockActorProvider_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActorProvider_Run_Call) Return(err error) *MockActorProvider_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_Run_Call) RunAndReturn(run func(ctx context.Context) error) *MockActorProvider_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) SetAlarm(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq) error {
	ret := _mock.Called(ctx, ref1, req)

	if len(ret) == 0 {
		panic("no return value specified for SetAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.AlarmRef, components.SetAlarmReq) error); ok {
		r0 = returnFunc(ctx, ref1, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_SetAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAlarm'
type MockActorProvider_SetAlarm_Call struct {
	*mock.Call
}

// SetAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.AlarmRef
//   - req components.SetAlarmReq
func (_e *MockActorProvider_Expecter) SetAlarm(ctx any, ref1 any, req any) *MockActorProvider_SetAlarm_Call {
	return &MockActorProvider_SetAlarm_Call{Call: _e.mock.On("SetAlarm", ctx, ref1, req)}
}

func (_c *MockActorProvider_SetAlarm_Call) Run(run func(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq)) *MockActorProvider_SetAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.AlarmRef
		if args[1] != nil {
			arg1 = args[1].(ref.AlarmRef)
		}
		var arg2 components.SetAlarmReq
		if args[2] != nil {
			arg2 = args[2].(components.SetAlarmReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_SetAlarm_Call) Return(err error) *MockActorProvider_SetAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_SetAlarm_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.AlarmRef, req components.SetAlarmReq) error) *MockActorProvider_SetAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) SetState(ctx context.Context, ref1 ref.ActorRef, data []byte, opts components.SetStateOpts) error {
	ret := _mock.Called(ctx, ref1, data, opts)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ref.ActorRef, []byte, components.SetStateOpts) error); ok {
		r0 = returnFunc(ctx, ref1, data, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockActorProvider_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx context.Context
//   - ref1 ref.ActorRef
//   - data []byte
//   - opts components.SetStateOpts
func (_e *MockActorProvider_Expecter) SetState(ctx any, ref1 any, data any, opts any) *MockActorProvider_SetState_Call {
	return &MockActorProvider_SetState_Call{Call: _e.mock.On("SetState", ctx, ref1, data, opts)}
}

func (_c *MockActorProvider_SetState_Call) Run(run func(ctx context.Context, ref1 ref.ActorRef, data []byte, opts components.SetStateOpts)) *MockActorProvider_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ref.ActorRef
		if args[1] != nil {
			arg1 = args[1].(ref.ActorRef)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 components.SetStateOpts
		if args[3] != nil {
			arg3 = args[3].(components.SetStateOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActorProvider_SetState_Call) Return(err error) *MockActorProvider_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_SetState_Call) RunAndReturn(run func(ctx context.Context, ref1 ref.ActorRef, data []byte, opts components.SetStateOpts) error) *MockActorProvider_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterHost provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) UnregisterHost(ctx context.Context, hostID string) error {
	ret := _mock.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterHost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hostID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_UnregisterHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterHost'
type MockActorProvider_UnregisterHost_Call struct {
	*mock.Call
}

// UnregisterHost is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID string
func (_e *MockActorProvider_Expecter) UnregisterHost(ctx any, hostID any) *MockActorProvider_UnregisterHost_Call {
	return &MockActorProvider_UnregisterHost_Call{Call: _e.mock.On("UnregisterHost", ctx, hostID)}
}

func (_c *MockActorProvider_UnregisterHost_Call) Run(run func(ctx context.Context, hostID string)) *MockActorProvider_UnregisterHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorProvider_UnregisterHost_Call) Return(err error) *MockActorProvider_UnregisterHost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_UnregisterHost_Call) RunAndReturn(run func(ctx context.Context, hostID string) error) *MockActorProvider_UnregisterHost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActorHost provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) UpdateActorHost(ctx context.Context, hostID string, req components.UpdateActorHostReq) error {
	ret := _mock.Called(ctx, hostID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActorHost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.UpdateActorHostReq) error); ok {
		r0 = returnFunc(ctx, hostID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_UpdateActorHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActorHost'
type MockActorProvider_UpdateActorHost_Call struct {
	*mock.Call
}

// UpdateActorHost is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID string
//   - req components.UpdateActorHostReq
func (_e *MockActorProvider_Expecter) UpdateActorHost(ctx any, hostID any, req any) *MockActorProvider_UpdateActorHost_Call {
	return &MockActorProvider_UpdateActorHost_Call{Call: _e.mock.On("UpdateActorHost", ctx, hostID, req)}
}

func (_c *MockActorProvider_UpdateActorHost_Call) Run(run func(ctx context.Context, hostID string, req components.UpdateActorHostReq)) *MockActorProvider_UpdateActorHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 components.UpdateActorHostReq
		if args[2] != nil {
			arg2 = args[2].(components.UpdateActorHostReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_UpdateActorHost_Call) Return(err error) *MockActorProvider_UpdateActorHost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_UpdateActorHost_Call) RunAndReturn(run func(ctx context.Context, hostID string, req components.UpdateActorHostReq) error) *MockActorProvider_UpdateActorHost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLeasedAlarm provides a mock function for the type MockActorProvider
func (_mock *MockActorProvider) UpdateLeasedAlarm(ctx context.Context, lease *ref.AlarmLease, req components.UpdateLeasedAlarmReq) error {
	ret := _mock.Called(ctx, lease, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLeasedAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ref.AlarmLease, components.UpdateLeasedAlarmReq) error); ok {
		r0 = returnFunc(ctx, lease, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorProvider_UpdateLeasedAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLeasedAlarm'
type MockActorProvider_UpdateLeasedAlarm_Call struct {
	*mock.Call
}

// UpdateLeasedAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - lease *ref.AlarmLease
//   - req components.UpdateLeasedAlarmReq
func (_e *MockActorProvider_Expecter) UpdateLeasedAlarm(ctx any, lease any, req any) *MockActorProvider_UpdateLeasedAlarm_Call {
	return &MockActorProvider_UpdateLeasedAlarm_Call{Call: _e.mock.On("UpdateLeasedAlarm", ctx, lease, req)}
}

func (_c *MockActorProvider_UpdateLeasedAlarm_Call) Run(run func(ctx context.Context, lease *ref.AlarmLease, req components.UpdateLeasedAlarmReq)) *MockActorProvider_UpdateLeasedAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ref.AlarmLease
		if args[1] != nil {
			arg1 = args[1].(*ref.AlarmLease)
		}
		var arg2 components.UpdateLeasedAlarmReq
		if args[2] != nil {
			arg2 = args[2].(components.UpdateLeasedAlarmReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorProvider_UpdateLeasedAlarm_Call) Return(err error) *MockActorProvider_UpdateLeasedAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorProvider_UpdateLeasedAlarm_Call) RunAndReturn(run func(ctx context.Context, lease *ref.AlarmLease, req components.UpdateLeasedAlarmReq) error) *MockActorProvider_UpdateLeasedAlarm_Call {
	_c.Call.Return(run)
	return _c
}
