//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package components_mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExclusiveController creates a new instance of MockExclusiveController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExclusiveController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExclusiveController {
	mock := &MockExclusiveController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExclusiveController is an autogenerated mock type for the ExclusiveController type
type MockExclusiveController struct {
	mock.Mock
}

type MockExclusiveController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExclusiveController) EXPECT() *MockExclusiveController_Expecter {
	return &MockExclusiveController_Expecter{mock: &_m.Mock}
}

// AcquireExclusiveLease provides a mock function for the type MockExclusiveController
func (_mock *MockExclusiveController) AcquireExclusiveLease(ctx context.Context, owner string, ttl time.Duration) (time.Time, error) {
	ret := _mock.Called(ctx, owner, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AcquireExclusiveLease")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (time.Time, error)); ok {
		return returnFunc(ctx, owner, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) time.Time); ok {
		r0 = returnFunc(ctx, owner, ttl)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, owner, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExclusiveController_AcquireExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireExclusiveLease'
type MockExclusiveController_AcquireExclusiveLease_Call struct {
	*mock.Call
}

// AcquireExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - ttl time.Duration
func (_e *MockExclusiveController_Expecter) AcquireExclusiveLease(ctx any, owner any, ttl any) *MockExclusiveController_AcquireExclusiveLease_Call {
	return &MockExclusiveController_AcquireExclusiveLease_Call{Call: _e.mock.On("AcquireExclusiveLease", ctx, owner, ttl)}
}

func (_c *MockExclusiveController_AcquireExclusiveLease_Call) Run(run func(ctx context.Context, owner string, ttl time.Duration)) *MockExclusiveController_AcquireExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExclusiveController_AcquireExclusiveLease_Call) Return(expiresAt time.Time, err error) *MockExclusiveController_AcquireExclusiveLease_Call {
	_c.Call.Return(expiresAt, err)
	return _c
}

func (_c *MockExclusiveController_AcquireExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string, ttl time.Duration) (time.Time, error)) *MockExclusiveController_AcquireExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseExclusiveLease provides a mock function for the type MockExclusiveController
func (_mock *MockExclusiveController) ReleaseExclusiveLease(ctx context.Context, owner string) error {
	ret := _mock.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseExclusiveLease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, owner)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExclusiveController_ReleaseExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseExclusiveLease'
type MockExclusiveController_ReleaseExclusiveLease_Call struct {
	*mock.Call
}

// ReleaseExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
func (_e *MockExclusiveController_Expecter) ReleaseExclusiveLease(ctx any, owner any) *MockExclusiveController_ReleaseExclusiveLease_Call {
	return &MockExclusiveController_ReleaseExclusiveLease_Call{Call: _e.mock.On("ReleaseExclusiveLease", ctx, owner)}
}

func (_c *MockExclusiveController_ReleaseExclusiveLease_Call) Run(run func(ctx context.Context, owner string)) *MockExclusiveController_ReleaseExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExclusiveController_ReleaseExclusiveLease_Call) Return(err error) *MockExclusiveController_ReleaseExclusiveLease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExclusiveController_ReleaseExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string) error) *MockExclusiveController_ReleaseExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// RenewExclusiveLease provides a mock function for the type MockExclusiveController
func (_mock *MockExclusiveController) RenewExclusiveLease(ctx context.Context, owner string, ttl time.Duration) (time.Time, error) {
	ret := _mock.Called(ctx, owner, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RenewExclusiveLease")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (time.Time, error)); ok {
		return returnFunc(ctx, owner, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) time.Time); ok {
		r0 = returnFunc(ctx, owner, ttl)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, owner, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExclusiveController_RenewExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewExclusiveLease'
type MockExclusiveController_RenewExclusiveLease_Call struct {
	*mock.Call
}

// RenewExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - ttl time.Duration
func (_e *MockExclusiveController_Expecter) RenewExclusiveLease(ctx any, owner any, ttl any) *MockExclusiveController_RenewExclusiveLease_Call {
	return &MockExclusiveController_RenewExclusiveLease_Call{Call: _e.mock.On("RenewExclusiveLease", ctx, owner, ttl)}
}

func (_c *MockExclusiveController_RenewExclusiveLease_Call) Run(run func(ctx context.Context, owner string, ttl time.Duration)) *MockExclusiveController_RenewExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExclusiveController_RenewExclusiveLease_Call) Return(expiresAt time.Time, err error) *MockExclusiveController_RenewExclusiveLease_Call {
	_c.Call.Return(expiresAt, err)
	return _c
}

func (_c *MockExclusiveController_RenewExclusiveLease_Call) RunAndReturn(run func(ctx context.Context, owner string, ttl time.Duration) (time.Time, error)) *MockExclusiveController_RenewExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}
