//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package components_mocks

import (
	"context"

	"github.com/italypaleale/francis/components"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManagementProvider creates a new instance of MockManagementProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagementProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagementProvider {
	mock := &MockManagementProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagementProvider is an autogenerated mock type for the ManagementProvider type
type MockManagementProvider struct {
	mock.Mock
}

type MockManagementProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagementProvider) EXPECT() *MockManagementProvider_Expecter {
	return &MockManagementProvider_Expecter{mock: &_m.Mock}
}

// ClearHostDraining provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ClearHostDraining(ctx context.Context, hostID string) error {
	ret := _mock.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for ClearHostDraining")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hostID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManagementProvider_ClearHostDraining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHostDraining'
type MockManagementProvider_ClearHostDraining_Call struct {
	*mock.Call
}

// ClearHostDraining is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID string
func (_e *MockManagementProvider_Expecter) ClearHostDraining(ctx any, hostID any) *MockManagementProvider_ClearHostDraining_Call {
	return &MockManagementProvider_ClearHostDraining_Call{Call: _e.mock.On("ClearHostDraining", ctx, hostID)}
}

func (_c *MockManagementProvider_ClearHostDraining_Call) Run(run func(ctx context.Context, hostID string)) *MockManagementProvider_ClearHostDraining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ClearHostDraining_Call) Return(err error) *MockManagementProvider_ClearHostDraining_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManagementProvider_ClearHostDraining_Call) RunAndReturn(run func(ctx context.Context, hostID string) error) *MockManagementProvider_ClearHostDraining_Call {
	_c.Call.Return(run)
	return _c
}

// CountJobs provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) CountJobs(ctx context.Context, req components.CountJobsReq) (int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountJobs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CountJobsReq) (int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CountJobsReq) int); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.CountJobsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_CountJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountJobs'
type MockManagementProvider_CountJobs_Call struct {
	*mock.Call
}

// CountJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.CountJobsReq
func (_e *MockManagementProvider_Expecter) CountJobs(ctx any, req any) *MockManagementProvider_CountJobs_Call {
	return &MockManagementProvider_CountJobs_Call{Call: _e.mock.On("CountJobs", ctx, req)}
}

func (_c *MockManagementProvider_CountJobs_Call) Run(run func(ctx context.Context, req components.CountJobsReq)) *MockManagementProvider_CountJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.CountJobsReq
		if args[1] != nil {
			arg1 = args[1].(components.CountJobsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_CountJobs_Call) Return(n int, err error) *MockManagementProvider_CountJobs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockManagementProvider_CountJobs_Call) RunAndReturn(run func(ctx context.Context, req components.CountJobsReq) (int, error)) *MockManagementProvider_CountJobs_Call {
	_c.Call.Return(run)
	return _c
}

// CountStates provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) CountStates(ctx context.Context, req components.CountStatesReq) (int, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountStates")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CountStatesReq) (int, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CountStatesReq) int); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.CountStatesReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_CountStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountStates'
type MockManagementProvider_CountStates_Call struct {
	*mock.Call
}

// CountStates is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.CountStatesReq
func (_e *MockManagementProvider_Expecter) CountStates(ctx any, req any) *MockManagementProvider_CountStates_Call {
	return &MockManagementProvider_CountStates_Call{Call: _e.mock.On("CountStates", ctx, req)}
}

func (_c *MockManagementProvider_CountStates_Call) Run(run func(ctx context.Context, req components.CountStatesReq)) *MockManagementProvider_CountStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.CountStatesReq
		if args[1] != nil {
			arg1 = args[1].(components.CountStatesReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_CountStates_Call) Return(n int, err error) *MockManagementProvider_CountStates_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockManagementProvider_CountStates_Call) RunAndReturn(run func(ctx context.Context, req components.CountStatesReq) (int, error)) *MockManagementProvider_CountStates_Call {
	_c.Call.Return(run)
	return _c
}

// GetExclusiveLease provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) GetExclusiveLease(ctx context.Context) (components.ExclusiveLeaseInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExclusiveLease")
	}

	var r0 components.ExclusiveLeaseInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (components.ExclusiveLeaseInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) components.ExclusiveLeaseInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(components.ExclusiveLeaseInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_GetExclusiveLease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExclusiveLease'
type MockManagementProvider_GetExclusiveLease_Call struct {
	*mock.Call
}

// GetExclusiveLease is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManagementProvider_Expecter) GetExclusiveLease(ctx any) *MockManagementProvider_GetExclusiveLease_Call {
	return &MockManagementProvider_GetExclusiveLease_Call{Call: _e.mock.On("GetExclusiveLease", ctx)}
}

func (_c *MockManagementProvider_GetExclusiveLease_Call) Run(run func(ctx context.Context)) *MockManagementProvider_GetExclusiveLease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagementProvider_GetExclusiveLease_Call) Return(exclusiveLeaseInfo components.ExclusiveLeaseInfo, err error) *MockManagementProvider_GetExclusiveLease_Call {
	_c.Call.Return(exclusiveLeaseInfo, err)
	return _c
}

func (_c *MockManagementProvider_GetExclusiveLease_Call) RunAndReturn(run func(ctx context.Context) (components.ExclusiveLeaseInfo, error)) *MockManagementProvider_GetExclusiveLease_Call {
	_c.Call.Return(run)
	return _c
}

// GetHostDetails provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) GetHostDetails(ctx context.Context, hostID string) (components.HostDetails, error) {
	ret := _mock.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for GetHostDetails")
	}

	var r0 components.HostDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (components.HostDetails, error)); ok {
		return returnFunc(ctx, hostID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) components.HostDetails); ok {
		r0 = returnFunc(ctx, hostID)
	} else {
		r0 = ret.Get(0).(components.HostDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hostID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_GetHostDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHostDetails'
type MockManagementProvider_GetHostDetails_Call struct {
	*mock.Call
}

// GetHostDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID string
func (_e *MockManagementProvider_Expecter) GetHostDetails(ctx any, hostID any) *MockManagementProvider_GetHostDetails_Call {
	return &MockManagementProvider_GetHostDetails_Call{Call: _e.mock.On("GetHostDetails", ctx, hostID)}
}

func (_c *MockManagementProvider_GetHostDetails_Call) Run(run func(ctx context.Context, hostID string)) *MockManagementProvider_GetHostDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_GetHostDetails_Call) Return(hostDetails components.HostDetails, err error) *MockManagementProvider_GetHostDetails_Call {
	_c.Call.Return(hostDetails, err)
	return _c
}

func (_c *MockManagementProvider_GetHostDetails_Call) RunAndReturn(run func(ctx context.Context, hostID string) (components.HostDetails, error)) *MockManagementProvider_GetHostDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ListAlarms provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListAlarms(ctx context.Context, req components.ListAlarmsReq) (components.ListAlarmsRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAlarms")
	}

	var r0 components.ListAlarmsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListAlarmsReq) (components.ListAlarmsRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListAlarmsReq) components.ListAlarmsRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.ListAlarmsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.ListAlarmsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListAlarms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAlarms'
type MockManagementProvider_ListAlarms_Call struct {
	*mock.Call
}

// ListAlarms is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.ListAlarmsReq
func (_e *MockManagementProvider_Expecter) ListAlarms(ctx any, req any) *MockManagementProvider_ListAlarms_Call {
	return &MockManagementProvider_ListAlarms_Call{Call: _e.mock.On("ListAlarms", ctx, req)}
}

func (_c *MockManagementProvider_ListAlarms_Call) Run(run func(ctx context.Context, req components.ListAlarmsReq)) *MockManagementProvider_ListAlarms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.ListAlarmsReq
		if args[1] != nil {
			arg1 = args[1].(components.ListAlarmsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListAlarms_Call) Return(listAlarmsRes components.ListAlarmsRes, err error) *MockManagementProvider_ListAlarms_Call {
	_c.Call.Return(listAlarmsRes, err)
	return _c
}

func (_c *MockManagementProvider_ListAlarms_Call) RunAndReturn(run func(ctx context.Context, req components.ListAlarmsReq) (components.ListAlarmsRes, error)) *MockManagementProvider_ListAlarms_Call {
	_c.Call.Return(run)
	return _c
}

// ListHostDetails provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListHostDetails(ctx context.Context, req components.ListHostDetailsReq) (components.ListHostDetailsRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListHostDetails")
	}

	var r0 components.ListHostDetailsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListHostDetailsReq) (components.ListHostDetailsRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListHostDetailsReq) components.ListHostDetailsRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.ListHostDetailsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.ListHostDetailsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListHostDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHostDetails'
type MockManagementProvider_ListHostDetails_Call struct {
	*mock.Call
}

// ListHostDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.ListHostDetailsReq
func (_e *MockManagementProvider_Expecter) ListHostDetails(ctx any, req any) *MockManagementProvider_ListHostDetails_Call {
	return &MockManagementProvider_ListHostDetails_Call{Call: _e.mock.On("ListHostDetails", ctx, req)}
}

func (_c *MockManagementProvider_ListHostDetails_Call) Run(run func(ctx context.Context, req components.ListHostDetailsReq)) *MockManagementProvider_ListHostDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.ListHostDetailsReq
		if args[1] != nil {
			arg1 = args[1].(components.ListHostDetailsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListHostDetails_Call) Return(listHostDetailsRes components.ListHostDetailsRes, err error) *MockManagementProvider_ListHostDetails_Call {
	_c.Call.Return(listHostDetailsRes, err)
	return _c
}

func (_c *MockManagementProvider_ListHostDetails_Call) RunAndReturn(run func(ctx context.Context, req components.ListHostDetailsReq) (components.ListHostDetailsRes, error)) *MockManagementProvider_ListHostDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacements provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListPlacements(ctx context.Context, req components.ListPlacementsReq) (components.ListPlacementsRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacements")
	}

	var r0 components.ListPlacementsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListPlacementsReq) (components.ListPlacementsRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListPlacementsReq) components.ListPlacementsRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.ListPlacementsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.ListPlacementsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListPlacements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacements'
type MockManagementProvider_ListPlacements_Call struct {
	*mock.Call
}

// ListPlacements is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.ListPlacementsReq
func (_e *MockManagementProvider_Expecter) ListPlacements(ctx any, req any) *MockManagementProvider_ListPlacements_Call {
	return &MockManagementProvider_ListPlacements_Call{Call: _e.mock.On("ListPlacements", ctx, req)}
}

func (_c *MockManagementProvider_ListPlacements_Call) Run(run func(ctx context.Context, req components.ListPlacementsReq)) *MockManagementProvider_ListPlacements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.ListPlacementsReq
		if args[1] != nil {
			arg1 = args[1].(components.ListPlacementsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListPlacements_Call) Return(listPlacementsRes components.ListPlacementsRes, err error) *MockManagementProvider_ListPlacements_Call {
	_c.Call.Return(listPlacementsRes, err)
	return _c
}

func (_c *MockManagementProvider_ListPlacements_Call) RunAndReturn(run func(ctx context.Context, req components.ListPlacementsReq) (components.ListPlacementsRes, error)) *MockManagementProvider_ListPlacements_Call {
	_c.Call.Return(run)
	return _c
}

// ListRuntimes provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListRuntimes(ctx context.Context) ([]components.RuntimeInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRuntimes")
	}

	var r0 []components.RuntimeInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]components.RuntimeInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []components.RuntimeInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]components.RuntimeInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListRuntimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRuntimes'
type MockManagementProvider_ListRuntimes_Call struct {
	*mock.Call
}

// ListRuntimes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManagementProvider_Expecter) ListRuntimes(ctx any) *MockManagementProvider_ListRuntimes_Call {
	return &MockManagementProvider_ListRuntimes_Call{Call: _e.mock.On("ListRuntimes", ctx)}
}

func (_c *MockManagementProvider_ListRuntimes_Call) Run(run func(ctx context.Context)) *MockManagementProvider_ListRuntimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListRuntimes_Call) Return(runtimeInfos []components.RuntimeInfo, err error) *MockManagementProvider_ListRuntimes_Call {
	_c.Call.Return(runtimeInfos, err)
	return _c
}

func (_c *MockManagementProvider_ListRuntimes_Call) RunAndReturn(run func(ctx context.Context) ([]components.RuntimeInfo, error)) *MockManagementProvider_ListRuntimes_Call {
	_c.Call.Return(run)
	return _c
}

// ListStateActorTypes provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListStateActorTypes(ctx context.Context, prefix string) ([]string, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ListStateActorTypes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListStateActorTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStateActorTypes'
type MockManagementProvider_ListStateActorTypes_Call struct {
	*mock.Call
}

// ListStateActorTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockManagementProvider_Expecter) ListStateActorTypes(ctx any, prefix any) *MockManagementProvider_ListStateActorTypes_Call {
	return &MockManagementProvider_ListStateActorTypes_Call{Call: _e.mock.On("ListStateActorTypes", ctx, prefix)}
}

func (_c *MockManagementProvider_ListStateActorTypes_Call) Run(run func(ctx context.Context, prefix string)) *MockManagementProvider_ListStateActorTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListStateActorTypes_Call) Return(strings []string, err error) *MockManagementProvider_ListStateActorTypes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockManagementProvider_ListStateActorTypes_Call) RunAndReturn(run func(ctx context.Context, prefix string) ([]string, error)) *MockManagementProvider_ListStateActorTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkflowEvents provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) ListWorkflowEvents(ctx context.Context, req components.ListWorkflowEventsReq) (components.ListWorkflowEventsRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkflowEvents")
	}

	var r0 components.ListWorkflowEventsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListWorkflowEventsReq) (components.ListWorkflowEventsRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.ListWorkflowEventsReq) components.ListWorkflowEventsRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.ListWorkflowEventsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.ListWorkflowEventsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_ListWorkflowEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkflowEvents'
type MockManagementProvider_ListWorkflowEvents_Call struct {
	*mock.Call
}

// ListWorkflowEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.ListWorkflowEventsReq
func (_e *MockManagementProvider_Expecter) ListWorkflowEvents(ctx any, req any) *MockManagementProvider_ListWorkflowEvents_Call {
	return &MockManagementProvider_ListWorkflowEvents_Call{Call: _e.mock.On("ListWorkflowEvents", ctx, req)}
}

func (_c *MockManagementProvider_ListWorkflowEvents_Call) Run(run func(ctx context.Context, req components.ListWorkflowEventsReq)) *MockManagementProvider_ListWorkflowEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.ListWorkflowEventsReq
		if args[1] != nil {
			arg1 = args[1].(components.ListWorkflowEventsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_ListWorkflowEvents_Call) Return(listWorkflowEventsRes components.ListWorkflowEventsRes, err error) *MockManagementProvider_ListWorkflowEvents_Call {
	_c.Call.Return(listWorkflowEventsRes, err)
	return _c
}

func (_c *MockManagementProvider_ListWorkflowEvents_Call) RunAndReturn(run func(ctx context.Context, req components.ListWorkflowEventsReq) (components.ListWorkflowEventsRes, error)) *MockManagementProvider_ListWorkflowEvents_Call {
	_c.Call.Return(run)
	return _c
}

// MarkHostDraining provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) MarkHostDraining(ctx context.Context, req components.MarkHostDrainingReq) (components.MarkHostDrainingRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MarkHostDraining")
	}

	var r0 components.MarkHostDrainingRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.MarkHostDrainingReq) (components.MarkHostDrainingRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.MarkHostDrainingReq) components.MarkHostDrainingRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.MarkHostDrainingRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.MarkHostDrainingReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_MarkHostDraining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkHostDraining'
type MockManagementProvider_MarkHostDraining_Call struct {
	*mock.Call
}

// MarkHostDraining is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.MarkHostDrainingReq
func (_e *MockManagementProvider_Expecter) MarkHostDraining(ctx any, req any) *MockManagementProvider_MarkHostDraining_Call {
	return &MockManagementProvider_MarkHostDraining_Call{Call: _e.mock.On("MarkHostDraining", ctx, req)}
}

func (_c *MockManagementProvider_MarkHostDraining_Call) Run(run func(ctx context.Context, req components.MarkHostDrainingReq)) *MockManagementProvider_MarkHostDraining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.MarkHostDrainingReq
		if args[1] != nil {
			arg1 = args[1].(components.MarkHostDrainingReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_MarkHostDraining_Call) Return(markHostDrainingRes components.MarkHostDrainingRes, err error) *MockManagementProvider_MarkHostDraining_Call {
	_c.Call.Return(markHostDrainingRes, err)
	return _c
}

func (_c *MockManagementProvider_MarkHostDraining_Call) RunAndReturn(run func(ctx context.Context, req components.MarkHostDrainingReq) (components.MarkHostDrainingRes, error)) *MockManagementProvider_MarkHostDraining_Call {
	_c.Call.Return(run)
	return _c
}

// QueryJobs provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) QueryJobs(ctx context.Context, req components.QueryJobsReq) (components.QueryJobsRes, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryJobs")
	}

	var r0 components.QueryJobsRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.QueryJobsReq) (components.QueryJobsRes, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.QueryJobsReq) components.QueryJobsRes); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(components.QueryJobsRes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.QueryJobsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagementProvider_QueryJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryJobs'
type MockManagementProvider_QueryJobs_Call struct {
	*mock.Call
}

// QueryJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.QueryJobsReq
func (_e *MockManagementProvider_Expecter) QueryJobs(ctx any, req any) *MockManagementProvider_QueryJobs_Call {
	return &MockManagementProvider_QueryJobs_Call{Call: _e.mock.On("QueryJobs", ctx, req)}
}

func (_c *MockManagementProvider_QueryJobs_Call) Run(run func(ctx context.Context, req components.QueryJobsReq)) *MockManagementProvider_QueryJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.QueryJobsReq
		if args[1] != nil {
			arg1 = args[1].(components.QueryJobsReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_QueryJobs_Call) Return(queryJobsRes components.QueryJobsRes, err error) *MockManagementProvider_QueryJobs_Call {
	_c.Call.Return(queryJobsRes, err)
	return _c
}

func (_c *MockManagementProvider_QueryJobs_Call) RunAndReturn(run func(ctx context.Context, req components.QueryJobsReq) (components.QueryJobsRes, error)) *MockManagementProvider_QueryJobs_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterRuntime provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) RegisterRuntime(ctx context.Context, req components.RegisterRuntimeReq) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterRuntime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.RegisterRuntimeReq) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManagementProvider_RegisterRuntime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRuntime'
type MockManagementProvider_RegisterRuntime_Call struct {
	*mock.Call
}

// RegisterRuntime is a helper method to define mock.On call
//   - ctx context.Context
//   - req components.RegisterRuntimeReq
func (_e *MockManagementProvider_Expecter) RegisterRuntime(ctx any, req any) *MockManagementProvider_RegisterRuntime_Call {
	return &MockManagementProvider_RegisterRuntime_Call{Call: _e.mock.On("RegisterRuntime", ctx, req)}
}

func (_c *MockManagementProvider_RegisterRuntime_Call) Run(run func(ctx context.Context, req components.RegisterRuntimeReq)) *MockManagementProvider_RegisterRuntime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.RegisterRuntimeReq
		if args[1] != nil {
			arg1 = args[1].(components.RegisterRuntimeReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagementProvider_RegisterRuntime_Call) Return(err error) *MockManagementProvider_RegisterRuntime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManagementProvider_RegisterRuntime_Call) RunAndReturn(run func(ctx context.Context, req components.RegisterRuntimeReq) error) *MockManagementProvider_RegisterRuntime_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterRuntime provides a mock function for the type MockManagementProvider
func (_mock *MockManagementProvider) UnregisterRuntime(ctx context.Context, runtimeID string, address string) error {
	ret := _mock.Called(ctx, runtimeID, address)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterRuntime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, runtimeID, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManagementProvider_UnregisterRuntime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterRuntime'
type MockManagementProvider_UnregisterRuntime_Call struct {
	*mock.Call
}

// UnregisterRuntime is a helper method to define mock.On call
//   - ctx context.Context
//   - runtimeID string
//   - address string
func (_e *MockManagementProvider_Expecter) UnregisterRuntime(ctx any, runtimeID any, address any) *MockManagementProvider_UnregisterRuntime_Call {
	return &MockManagementProvider_UnregisterRuntime_Call{Call: _e.mock.On("UnregisterRuntime", ctx, runtimeID, address)}
}

func (_c *MockManagementProvider_UnregisterRuntime_Call) Run(run func(ctx context.Context, runtimeID string, address string)) *MockManagementProvider_UnregisterRuntime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManagementProvider_UnregisterRuntime_Call) Return(err error) *MockManagementProvider_UnregisterRuntime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManagementProvider_UnregisterRuntime_Call) RunAndReturn(run func(ctx context.Context, runtimeID string, address string) error) *MockManagementProvider_UnregisterRuntime_Call {
	_c.Call.Return(run)
	return _c
}
