//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package components_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderOptions creates a new instance of MockProviderOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderOptions {
	mock := &MockProviderOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderOptions is an autogenerated mock type for the ProviderOptions type
type MockProviderOptions struct {
	mock.Mock
}

type MockProviderOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderOptions) EXPECT() *MockProviderOptions_Expecter {
	return &MockProviderOptions_Expecter{mock: &_m.Mock}
}
