{{/*
Base name of the chart, overridable with nameOverride
*/}}
{{- define "francis.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Fully qualified name used for the resources this chart creates
*/}}
{{- define "francis.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{- define "francis.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "francis.selectorLabels" -}}
app.kubernetes.io/name: {{ include "francis.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "francis.labels" -}}
helm.sh/chart: {{ include "francis.chart" . }}
{{ include "francis.selectorLabels" . }}
app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.tag | trunc 63 | trimSuffix "-" | quote }}
app.kubernetes.io/component: runtime
app.kubernetes.io/part-of: francis
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end }}

{{- define "francis.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "francis.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Name of the headless Service, which gives every replica a stable per-pod DNS name
*/}}
{{- define "francis.headlessServiceName" -}}
{{- printf "%s-headless" (include "francis.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Name of the Secret holding the runtime config file, which is the user-provided one when existingConfigSecret is set
*/}}
{{- define "francis.configSecretName" -}}
{{- if .Values.existingConfigSecret }}
{{- .Values.existingConfigSecret }}
{{- else }}
{{- printf "%s-config" (include "francis.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{- define "francis.configSecretKey" -}}
{{- if .Values.existingConfigSecret }}
{{- default "config.yaml" .Values.existingConfigSecretKey }}
{{- else }}
{{- print "config.yaml" }}
{{- end }}
{{- end }}

{{/*
Container image reference, preferring the digest over the tag when both are set
*/}}
{{- define "francis.image" -}}
{{- if .Values.image.digest }}
{{- printf "%s@%s" .Values.image.repository .Values.image.digest }}
{{- else }}
{{- printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
{{- end }}
{{- end }}

{{/*
Normalized database type
*/}}
{{- define "francis.databaseType" -}}
{{- lower (default "" .Values.database.type) }}
{{- end }}

{{/*
Reports whether the chart manages a SQLite data volume, which is skipped entirely when the config comes from an existing Secret
*/}}
{{- define "francis.sqliteVolumeEnabled" -}}
{{- if eq (include "francis.databaseType" .) "sqlite" }}
{{- if .Values.database.sqlite.persistence.enabled }}
{{- print "true" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Connection string passed to the runtime, from which the runtime infers the backend
*/}}
{{- define "francis.connectionString" -}}
{{- if eq (include "francis.databaseType" .) "postgres" }}
{{- .Values.database.postgres.connectionString }}
{{- else }}
{{- .Values.database.sqlite.path }}
{{- end }}
{{- end }}

{{/*
The runtime configuration file
*/}}
{{- define "francis.configFile" -}}
# Generated by the francis Helm chart, do not edit
# The runtime serves WebTransport over HTTP/3, so this port is bound over UDP
bind: "0.0.0.0:{{ .Values.service.port }}"
{{- with .Values.runtimeId }}
runtimeId: {{ . | quote }}
{{- end }}

runtimePSKs:
{{- range .Values.runtimePSKs }}
  - {{ . | quote }}
{{- end }}

bootstrap:
  method: {{ lower .Values.bootstrap.method | quote }}
{{- if eq (lower .Values.bootstrap.method) "psk" }}
  hostPSK: {{ .Values.bootstrap.hostPSK | quote }}
{{- else }}
  jwt:
    issuer: {{ .Values.bootstrap.jwt.issuer | quote }}
    audience: {{ .Values.bootstrap.jwt.audience | quote }}
    {{- with .Values.bootstrap.jwt.jwksURL }}
    jwksURL: {{ . | quote }}
    {{- end }}
    {{- with .Values.bootstrap.jwt.staticJWKS }}
    staticJWKS: {{ . | quote }}
    {{- end }}
{{- end }}

provider:
  connectionString: {{ include "francis.connectionString" . | quote }}
  queryLog:
    enabled: {{ .Values.database.queryLog.enabled }}
    includeParameters: {{ .Values.database.queryLog.includeParameters }}
    {{- with .Values.database.queryLog.slowThreshold }}
    slowThreshold: {{ . | quote }}
    {{- end }}
  operationLog:
    enabled: {{ .Values.database.operationLog.enabled }}
    {{- with .Values.database.operationLog.slowThreshold }}
    slowThreshold: {{ . | quote }}
    {{- end }}

{{- with .Values.tuning.workloadCertTTL }}
workloadCertTTL: {{ . | quote }}
{{- end }}
{{- with .Values.tuning.healthCheckDeadline }}
healthCheckDeadline: {{ . | quote }}
{{- end }}
{{- with .Values.tuning.alarmsPollInterval }}
alarmsPollInterval: {{ . | quote }}
{{- end }}
{{- with .Values.tuning.alarmsLeaseDuration }}
alarmsLeaseDuration: {{ . | quote }}
{{- end }}
{{- with .Values.tuning.shutdownGracePeriod }}
shutdownGracePeriod: {{ . | quote }}
{{- end }}
{{- if gt (int .Values.tuning.maxHosts) 0 }}
maxHosts: {{ int .Values.tuning.maxHosts }}
{{- end }}

log:
  level: {{ .Values.log.level | quote }}
  json: {{ .Values.log.json }}
{{- end }}

{{/*
A container probe that runs the image's own healthcheck subcommand
It completes a full WebTransport handshake against the runtime on the loopback address, verifying its certificate against the cluster CA
Expects a dict with "probe" and, optionally, "successThreshold" set to true for probes that accept the field
*/}}
{{- define "francis.probe" -}}
exec:
  command:
    - /bin/francis
    - healthcheck
    - -timeout
    - {{ printf "%ds" (int .probe.timeoutSeconds) | quote }}
initialDelaySeconds: {{ int .probe.initialDelaySeconds }}
periodSeconds: {{ int .probe.periodSeconds }}
timeoutSeconds: {{ int .probe.timeoutSeconds }}
failureThreshold: {{ int .probe.failureThreshold }}
{{- if .successThreshold }}
successThreshold: {{ int .probe.successThreshold }}
{{- end }}
{{- end }}

{{/*
The standard OTEL_* variables the runtime reads, which is the only way its telemetry export is configured
*/}}
{{- define "francis.openTelemetryEnv" -}}
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: {{ .Values.openTelemetry.endpoint | quote }}
- name: OTEL_EXPORTER_OTLP_PROTOCOL
  value: {{ .Values.openTelemetry.protocol | quote }}
- name: OTEL_TRACES_EXPORTER
  value: {{ .Values.openTelemetry.traces | quote }}
- name: OTEL_METRICS_EXPORTER
  value: {{ .Values.openTelemetry.metrics | quote }}
- name: OTEL_LOGS_EXPORTER
  value: {{ .Values.openTelemetry.logs | quote }}
{{- with .Values.openTelemetry.sampler }}
- name: OTEL_TRACES_SAMPLER
  value: {{ . | quote }}
{{- end }}
{{- with .Values.openTelemetry.samplerArg }}
- name: OTEL_TRACES_SAMPLER_ARG
  value: {{ . | quote }}
{{- end }}
{{- end }}

{{/*
Fails the render with an actionable message when the values cannot produce a working install
Every template includes this so the error surfaces no matter which resource renders first
*/}}
{{- define "francis.validateValues" -}}
{{- $replicas := int .Values.replicaCount -}}
{{- if or (lt $replicas 1) (gt $replicas 4) -}}
{{- fail (printf "\nfrancis: replicaCount must be between 1 and 4, got %d" $replicas) -}}
{{- end -}}

{{- $type := include "francis.databaseType" . -}}
{{- if not (has $type (list "postgres" "sqlite")) -}}
{{- fail (printf "\nfrancis: database.type must be either \"postgres\" or \"sqlite\", got %q" (toString .Values.database.type)) -}}
{{- end -}}

{{- if and (eq $type "sqlite") (gt $replicas 1) -}}
{{- fail (printf "\nfrancis: database.type \"sqlite\" supports a single replica, but replicaCount is %d.\nA SQLite database can be owned by one runtime only. Set database.type to \"postgres\" to run more than one replica, or set replicaCount to 1." $replicas) -}}
{{- end -}}

{{- if eq $type "sqlite" -}}
{{- $path := default "" .Values.database.sqlite.path -}}
{{- if not $path -}}
{{- fail "\nfrancis: database.sqlite.path is required when database.type is \"sqlite\"" -}}
{{- end -}}
{{- $mountPath := default "" .Values.database.sqlite.persistence.mountPath -}}
{{- if not $mountPath -}}
{{- fail "\nfrancis: database.sqlite.persistence.mountPath is required when database.type is \"sqlite\"" -}}
{{- end -}}
{{- if not (contains $mountPath $path) -}}
{{- fail (printf "\nfrancis: database.sqlite.path (%q) is outside the mounted volume at database.sqlite.persistence.mountPath (%q), so the database would not survive a pod restart" $path $mountPath) -}}
{{- end -}}
{{- end -}}

{{/* Everything below configures the generated config file, which an existing Secret replaces wholesale */}}
{{- if not .Values.existingConfigSecret -}}

{{- if and (eq $type "postgres") (not .Values.database.postgres.connectionString) -}}
{{- fail "\nfrancis: database.postgres.connectionString is required when database.type is \"postgres\".\nPass it with --set database.postgres.connectionString=… or supply the whole config file with existingConfigSecret." -}}
{{- end -}}
{{- if eq $type "postgres" -}}
{{- $connString := lower .Values.database.postgres.connectionString -}}
{{- if not (or (hasPrefix "postgres://" $connString) (hasPrefix "postgresql://" $connString)) -}}
{{- fail "\nfrancis: database.postgres.connectionString must begin with \"postgres://\" or \"postgresql://\", which is how the runtime selects the PostgreSQL backend" -}}
{{- end -}}
{{- end -}}

{{- if not .Values.runtimePSKs -}}
{{- fail "\nfrancis: runtimePSKs is required, and holds the pre-shared keys the cluster CA is derived from.\nPass it with --set-string 'runtimePSKs[0]=…' or supply the whole config file with existingConfigSecret." -}}
{{- end -}}
{{- range $i, $psk := .Values.runtimePSKs -}}
{{- if not $psk -}}
{{- fail (printf "\nfrancis: runtimePSKs[%d] is empty" $i) -}}
{{- end -}}
{{- end -}}

{{- $method := lower (default "" .Values.bootstrap.method) -}}
{{- if not (has $method (list "psk" "jwt")) -}}
{{- fail (printf "\nfrancis: bootstrap.method must be either \"psk\" or \"jwt\", got %q" (toString .Values.bootstrap.method)) -}}
{{- end -}}
{{- if and (eq $method "psk") (not .Values.bootstrap.hostPSK) -}}
{{- fail "\nfrancis: bootstrap.hostPSK is required when bootstrap.method is \"psk\"" -}}
{{- end -}}
{{- if eq $method "jwt" -}}
{{- if not .Values.bootstrap.jwt.issuer -}}
{{- fail "\nfrancis: bootstrap.jwt.issuer is required when bootstrap.method is \"jwt\"" -}}
{{- end -}}
{{- if not .Values.bootstrap.jwt.audience -}}
{{- fail "\nfrancis: bootstrap.jwt.audience is required when bootstrap.method is \"jwt\"" -}}
{{- end -}}
{{- if and (not .Values.bootstrap.jwt.jwksURL) (not .Values.bootstrap.jwt.staticJWKS) -}}
{{- fail "\nfrancis: bootstrap.jwt requires either jwksURL or staticJWKS when bootstrap.method is \"jwt\"" -}}
{{- end -}}
{{- end -}}

{{- if not (has (lower (default "" .Values.log.level)) (list "debug" "info" "warn" "error")) -}}
{{- fail (printf "\nfrancis: log.level must be one of \"debug\", \"info\", \"warn\", or \"error\", got %q" (toString .Values.log.level)) -}}
{{- end -}}

{{- end -}}

{{- if and .Values.openTelemetry.enabled (not .Values.openTelemetry.endpoint) -}}
{{- fail "\nfrancis: openTelemetry.endpoint is required when openTelemetry.enabled is true" -}}
{{- end -}}
{{- end -}}
