{{- include "francis.validateValues" . -}}
{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "francis.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "francis.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "francis.configFile" . | nindent 4 }}
{{- end }}
