name: "CI Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GOLANGCI_LINT_VERSION: "v2.4.0"

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: "Lint"
        uses: golangci/golangci-lint-action@v8
        with:
          version: "${{ env.GOLANGCI_LINT_VERSION }}"

      - name: "Test"
        run: |
          go test -tags unit ./...
