name: "CI Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GOLANGCI_LINT_VERSION: "v2.4.0"

permissions:
  contents: "read"

jobs:
  ci:
    runs-on: "ubuntu-latest"

    services:
      postgres:
        image: "postgres:17-alpine"
        env:
          POSTGRES_USER: "actors"
          POSTGRES_PASSWORD: "actors"
          POSTGRES_DB: "actors"
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Check out code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: "Lint"
        uses: golangci/golangci-lint-action@v8
        with:
          version: "${{ env.GOLANGCI_LINT_VERSION }}"

      - name: "Test"
        env:
          TEST_POSTGRES_CONNSTRING: "postgres://actors:actors@localhost:5432/actors"
        run: |
          go test -v -tags unit ./...
