//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActorBootstrapper creates a new instance of MockActorBootstrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorBootstrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorBootstrapper {
	mock := &MockActorBootstrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorBootstrapper is an autogenerated mock type for the ActorBootstrapper type
type MockActorBootstrapper struct {
	mock.Mock
}

type MockActorBootstrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorBootstrapper) EXPECT() *MockActorBootstrapper_Expecter {
	return &MockActorBootstrapper_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function for the type MockActorBootstrapper
func (_mock *MockActorBootstrapper) Bootstrap(ctx context.Context, data any) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorBootstrapper_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockActorBootstrapper_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - ctx context.Context
//   - data any
func (_e *MockActorBootstrapper_Expecter) Bootstrap(ctx any, data any) *MockActorBootstrapper_Bootstrap_Call {
	return &MockActorBootstrapper_Bootstrap_Call{Call: _e.mock.On("Bootstrap", ctx, data)}
}

func (_c *MockActorBootstrapper_Bootstrap_Call) Run(run func(ctx context.Context, data any)) *MockActorBootstrapper_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActorBootstrapper_Bootstrap_Call) Return(err error) *MockActorBootstrapper_Bootstrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorBootstrapper_Bootstrap_Call) RunAndReturn(run func(ctx context.Context, data any) error) *MockActorBootstrapper_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}
