//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActorAlarm creates a new instance of MockActorAlarm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorAlarm(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorAlarm {
	mock := &MockActorAlarm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorAlarm is an autogenerated mock type for the ActorAlarm type
type MockActorAlarm struct {
	mock.Mock
}

type MockActorAlarm_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorAlarm) EXPECT() *MockActorAlarm_Expecter {
	return &MockActorAlarm_Expecter{mock: &_m.Mock}
}

// Alarm provides a mock function for the type MockActorAlarm
func (_mock *MockActorAlarm) Alarm(ctx context.Context, name string, data any) error {
	ret := _mock.Called(ctx, name, data)

	if len(ret) == 0 {
		panic("no return value specified for Alarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, name, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorAlarm_Alarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alarm'
type MockActorAlarm_Alarm_Call struct {
	*mock.Call
}

// Alarm is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - data any
func (_e *MockActorAlarm_Expecter) Alarm(ctx interface{}, name interface{}, data interface{}) *MockActorAlarm_Alarm_Call {
	return &MockActorAlarm_Alarm_Call{Call: _e.mock.On("Alarm", ctx, name, data)}
}

func (_c *MockActorAlarm_Alarm_Call) Run(run func(ctx context.Context, name string, data any)) *MockActorAlarm_Alarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorAlarm_Alarm_Call) Return(err error) *MockActorAlarm_Alarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorAlarm_Alarm_Call) RunAndReturn(run func(ctx context.Context, name string, data any) error) *MockActorAlarm_Alarm_Call {
	_c.Call.Return(run)
	return _c
}
