//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	"github.com/italypaleale/francis/actor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActorPeek creates a new instance of MockActorPeek. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorPeek(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorPeek {
	mock := &MockActorPeek{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorPeek is an autogenerated mock type for the ActorPeek type
type MockActorPeek struct {
	mock.Mock
}

type MockActorPeek_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorPeek) EXPECT() *MockActorPeek_Expecter {
	return &MockActorPeek_Expecter{mock: &_m.Mock}
}

// Peek provides a mock function for the type MockActorPeek
func (_mock *MockActorPeek) Peek(ctx context.Context, method string, data actor.Envelope) (any, error) {
	ret := _mock.Called(ctx, method, data)

	if len(ret) == 0 {
		panic("no return value specified for Peek")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, actor.Envelope) (any, error)); ok {
		return returnFunc(ctx, method, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, actor.Envelope) any); ok {
		r0 = returnFunc(ctx, method, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, actor.Envelope) error); ok {
		r1 = returnFunc(ctx, method, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActorPeek_Peek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peek'
type MockActorPeek_Peek_Call struct {
	*mock.Call
}

// Peek is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - data actor.Envelope
func (_e *MockActorPeek_Expecter) Peek(ctx any, method any, data any) *MockActorPeek_Peek_Call {
	return &MockActorPeek_Peek_Call{Call: _e.mock.On("Peek", ctx, method, data)}
}

func (_c *MockActorPeek_Peek_Call) Run(run func(ctx context.Context, method string, data actor.Envelope)) *MockActorPeek_Peek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 actor.Envelope
		if args[2] != nil {
			arg2 = args[2].(actor.Envelope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorPeek_Peek_Call) Return(v any, err error) *MockActorPeek_Peek_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockActorPeek_Peek_Call) RunAndReturn(run func(ctx context.Context, method string, data actor.Envelope) (any, error)) *MockActorPeek_Peek_Call {
	_c.Call.Return(run)
	return _c
}
