//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	"github.com/italypaleale/francis/actor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActorJobFailed creates a new instance of MockActorJobFailed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorJobFailed(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorJobFailed {
	mock := &MockActorJobFailed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorJobFailed is an autogenerated mock type for the ActorJobFailed type
type MockActorJobFailed struct {
	mock.Mock
}

type MockActorJobFailed_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorJobFailed) EXPECT() *MockActorJobFailed_Expecter {
	return &MockActorJobFailed_Expecter{mock: &_m.Mock}
}

// JobFailed provides a mock function for the type MockActorJobFailed
func (_mock *MockActorJobFailed) JobFailed(ctx context.Context, jobID string, method string, data actor.Envelope, jobErr error) error {
	ret := _mock.Called(ctx, jobID, method, data, jobErr)

	if len(ret) == 0 {
		panic("no return value specified for JobFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, actor.Envelope, error) error); ok {
		r0 = returnFunc(ctx, jobID, method, data, jobErr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorJobFailed_JobFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobFailed'
type MockActorJobFailed_JobFailed_Call struct {
	*mock.Call
}

// JobFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - method string
//   - data actor.Envelope
//   - jobErr error
func (_e *MockActorJobFailed_Expecter) JobFailed(ctx interface{}, jobID interface{}, method interface{}, data interface{}, jobErr interface{}) *MockActorJobFailed_JobFailed_Call {
	return &MockActorJobFailed_JobFailed_Call{Call: _e.mock.On("JobFailed", ctx, jobID, method, data, jobErr)}
}

func (_c *MockActorJobFailed_JobFailed_Call) Run(run func(ctx context.Context, jobID string, method string, data actor.Envelope, jobErr error)) *MockActorJobFailed_JobFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 actor.Envelope
		if args[3] != nil {
			arg3 = args[3].(actor.Envelope)
		}
		var arg4 error
		if args[4] != nil {
			arg4 = args[4].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockActorJobFailed_JobFailed_Call) Return(err error) *MockActorJobFailed_JobFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorJobFailed_JobFailed_Call) RunAndReturn(run func(ctx context.Context, jobID string, method string, data actor.Envelope, jobErr error) error) *MockActorJobFailed_JobFailed_Call {
	_c.Call.Return(run)
	return _c
}
