//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"
	"io"

	"github.com/italypaleale/francis/actor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActorStream creates a new instance of MockActorStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorStream {
	mock := &MockActorStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorStream is an autogenerated mock type for the ActorStream type
type MockActorStream struct {
	mock.Mock
}

type MockActorStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorStream) EXPECT() *MockActorStream_Expecter {
	return &MockActorStream_Expecter{mock: &_m.Mock}
}

// InvokeStream provides a mock function for the type MockActorStream
func (_mock *MockActorStream) InvokeStream(ctx context.Context, method string, reqContentType string, body io.Reader, w actor.StreamResponseWriter) error {
	ret := _mock.Called(ctx, method, reqContentType, body, w)

	if len(ret) == 0 {
		panic("no return value specified for InvokeStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, actor.StreamResponseWriter) error); ok {
		r0 = returnFunc(ctx, method, reqContentType, body, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorStream_InvokeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeStream'
type MockActorStream_InvokeStream_Call struct {
	*mock.Call
}

// InvokeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - reqContentType string
//   - body io.Reader
//   - w actor.StreamResponseWriter
func (_e *MockActorStream_Expecter) InvokeStream(ctx interface{}, method interface{}, reqContentType interface{}, body interface{}, w interface{}) *MockActorStream_InvokeStream_Call {
	return &MockActorStream_InvokeStream_Call{Call: _e.mock.On("InvokeStream", ctx, method, reqContentType, body, w)}
}

func (_c *MockActorStream_InvokeStream_Call) Run(run func(ctx context.Context, method string, reqContentType string, body io.Reader, w actor.StreamResponseWriter)) *MockActorStream_InvokeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 actor.StreamResponseWriter
		if args[4] != nil {
			arg4 = args[4].(actor.StreamResponseWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockActorStream_InvokeStream_Call) Return(err error) *MockActorStream_InvokeStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorStream_InvokeStream_Call) RunAndReturn(run func(ctx context.Context, method string, reqContentType string, body io.Reader, w actor.StreamResponseWriter) error) *MockActorStream_InvokeStream_Call {
	_c.Call.Return(run)
	return _c
}
