//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	"github.com/italypaleale/francis/actor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActorJob creates a new instance of MockActorJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorJob {
	mock := &MockActorJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorJob is an autogenerated mock type for the ActorJob type
type MockActorJob struct {
	mock.Mock
}

type MockActorJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorJob) EXPECT() *MockActorJob_Expecter {
	return &MockActorJob_Expecter{mock: &_m.Mock}
}

// Job provides a mock function for the type MockActorJob
func (_mock *MockActorJob) Job(ctx context.Context, method string, data actor.Envelope) error {
	ret := _mock.Called(ctx, method, data)

	if len(ret) == 0 {
		panic("no return value specified for Job")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, actor.Envelope) error); ok {
		r0 = returnFunc(ctx, method, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorJob_Job_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Job'
type MockActorJob_Job_Call struct {
	*mock.Call
}

// Job is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - data actor.Envelope
func (_e *MockActorJob_Expecter) Job(ctx any, method any, data any) *MockActorJob_Job_Call {
	return &MockActorJob_Job_Call{Call: _e.mock.On("Job", ctx, method, data)}
}

func (_c *MockActorJob_Job_Call) Run(run func(ctx context.Context, method string, data actor.Envelope)) *MockActorJob_Job_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 actor.Envelope
		if args[2] != nil {
			arg2 = args[2].(actor.Envelope)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActorJob_Job_Call) Return(err error) *MockActorJob_Job_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorJob_Job_Call) RunAndReturn(run func(ctx context.Context, method string, data actor.Envelope) error) *MockActorJob_Job_Call {
	_c.Call.Return(run)
	return _c
}
