//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActorDeactivate creates a new instance of MockActorDeactivate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActorDeactivate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActorDeactivate {
	mock := &MockActorDeactivate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActorDeactivate is an autogenerated mock type for the ActorDeactivate type
type MockActorDeactivate struct {
	mock.Mock
}

type MockActorDeactivate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActorDeactivate) EXPECT() *MockActorDeactivate_Expecter {
	return &MockActorDeactivate_Expecter{mock: &_m.Mock}
}

// Deactivate provides a mock function for the type MockActorDeactivate
func (_mock *MockActorDeactivate) Deactivate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockActorDeactivate_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockActorDeactivate_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActorDeactivate_Expecter) Deactivate(ctx interface{}) *MockActorDeactivate_Deactivate_Call {
	return &MockActorDeactivate_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx)}
}

func (_c *MockActorDeactivate_Deactivate_Call) Run(run func(ctx context.Context)) *MockActorDeactivate_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActorDeactivate_Deactivate_Call) Return(err error) *MockActorDeactivate_Deactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockActorDeactivate_Deactivate_Call) RunAndReturn(run func(ctx context.Context) error) *MockActorDeactivate_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}
