//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBootstrapper creates a new instance of MockBootstrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBootstrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBootstrapper {
	mock := &MockBootstrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBootstrapper is an autogenerated mock type for the ActorBootstrapper type
type MockBootstrapper struct {
	mock.Mock
}

type MockBootstrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBootstrapper) EXPECT() *MockBootstrapper_Expecter {
	return &MockBootstrapper_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function for the type MockBootstrapper
func (_mock *MockBootstrapper) Bootstrap(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBootstrapper_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockBootstrapper_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBootstrapper_Expecter) Bootstrap(ctx any) *MockBootstrapper_Bootstrap_Call {
	return &MockBootstrapper_Bootstrap_Call{Call: _e.mock.On("Bootstrap", ctx)}
}

func (_c *MockBootstrapper_Bootstrap_Call) Run(run func(ctx context.Context)) *MockBootstrapper_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBootstrapper_Bootstrap_Call) Return(err error) *MockBootstrapper_Bootstrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBootstrapper_Bootstrap_Call) RunAndReturn(run func(ctx context.Context) error) *MockBootstrapper_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}
