//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEnvelope creates a new instance of MockEnvelope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvelope(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvelope {
	mock := &MockEnvelope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnvelope is an autogenerated mock type for the Envelope type
type MockEnvelope struct {
	mock.Mock
}

type MockEnvelope_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvelope) EXPECT() *MockEnvelope_Expecter {
	return &MockEnvelope_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockEnvelope
func (_mock *MockEnvelope) Decode(into any) error {
	ret := _mock.Called(into)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(into)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnvelope_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockEnvelope_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - into any
func (_e *MockEnvelope_Expecter) Decode(into any) *MockEnvelope_Decode_Call {
	return &MockEnvelope_Decode_Call{Call: _e.mock.On("Decode", into)}
}

func (_c *MockEnvelope_Decode_Call) Run(run func(into any)) *MockEnvelope_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvelope_Decode_Call) Return(err error) *MockEnvelope_Decode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnvelope_Decode_Call) RunAndReturn(run func(into any) error) *MockEnvelope_Decode_Call {
	_c.Call.Return(run)
	return _c
}
