//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	"context"
	"io"

	"github.com/italypaleale/francis/actor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHost creates a new instance of MockHost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHost(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHost {
	mock := &MockHost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHost is an autogenerated mock type for the Host type
type MockHost struct {
	mock.Mock
}

type MockHost_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHost) EXPECT() *MockHost_Expecter {
	return &MockHost_Expecter{mock: &_m.Mock}
}

// CancelJob provides a mock function for the type MockHost
func (_mock *MockHost) CancelJob(ctx context.Context, actorType string, actorID string, jobID string) error {
	ret := _mock.Called(ctx, actorType, actorID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockHost_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - jobID string
func (_e *MockHost_Expecter) CancelJob(ctx any, actorType any, actorID any, jobID any) *MockHost_CancelJob_Call {
	return &MockHost_CancelJob_Call{Call: _e.mock.On("CancelJob", ctx, actorType, actorID, jobID)}
}

func (_c *MockHost_CancelJob_Call) Run(run func(ctx context.Context, actorType string, actorID string, jobID string)) *MockHost_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHost_CancelJob_Call) Return(err error) *MockHost_CancelJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_CancelJob_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, jobID string) error) *MockHost_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlarm provides a mock function for the type MockHost
func (_mock *MockHost) DeleteAlarm(ctx context.Context, actorType string, actorID string, name string) error {
	ret := _mock.Called(ctx, actorType, actorID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_DeleteAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlarm'
type MockHost_DeleteAlarm_Call struct {
	*mock.Call
}

// DeleteAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - name string
func (_e *MockHost_Expecter) DeleteAlarm(ctx any, actorType any, actorID any, name any) *MockHost_DeleteAlarm_Call {
	return &MockHost_DeleteAlarm_Call{Call: _e.mock.On("DeleteAlarm", ctx, actorType, actorID, name)}
}

func (_c *MockHost_DeleteAlarm_Call) Run(run func(ctx context.Context, actorType string, actorID string, name string)) *MockHost_DeleteAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHost_DeleteAlarm_Call) Return(err error) *MockHost_DeleteAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_DeleteAlarm_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, name string) error) *MockHost_DeleteAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteState provides a mock function for the type MockHost
func (_mock *MockHost) DeleteState(ctx context.Context, actorType string, actorID string) error {
	ret := _mock.Called(ctx, actorType, actorID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, actorType, actorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_DeleteState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteState'
type MockHost_DeleteState_Call struct {
	*mock.Call
}

// DeleteState is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
func (_e *MockHost_Expecter) DeleteState(ctx any, actorType any, actorID any) *MockHost_DeleteState_Call {
	return &MockHost_DeleteState_Call{Call: _e.mock.On("DeleteState", ctx, actorType, actorID)}
}

func (_c *MockHost_DeleteState_Call) Run(run func(ctx context.Context, actorType string, actorID string)) *MockHost_DeleteState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHost_DeleteState_Call) Return(err error) *MockHost_DeleteState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_DeleteState_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string) error) *MockHost_DeleteState_Call {
	_c.Call.Return(run)
	return _c
}

// Dispatch provides a mock function for the type MockHost
func (_mock *MockHost) Dispatch(ctx context.Context, actorType string, actorID string, method string, data any, properties actor.JobProperties) (string, error) {
	ret := _mock.Called(ctx, actorType, actorID, method, data, properties)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, actor.JobProperties) (string, error)); ok {
		return returnFunc(ctx, actorType, actorID, method, data, properties)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, actor.JobProperties) string); ok {
		r0 = returnFunc(ctx, actorType, actorID, method, data, properties)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, any, actor.JobProperties) error); ok {
		r1 = returnFunc(ctx, actorType, actorID, method, data, properties)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockHost_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - method string
//   - data any
//   - properties actor.JobProperties
func (_e *MockHost_Expecter) Dispatch(ctx any, actorType any, actorID any, method any, data any, properties any) *MockHost_Dispatch_Call {
	return &MockHost_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, actorType, actorID, method, data, properties)}
}

func (_c *MockHost_Dispatch_Call) Run(run func(ctx context.Context, actorType string, actorID string, method string, data any, properties actor.JobProperties)) *MockHost_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 actor.JobProperties
		if args[5] != nil {
			arg5 = args[5].(actor.JobProperties)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockHost_Dispatch_Call) Return(jobID string, err error) *MockHost_Dispatch_Call {
	_c.Call.Return(jobID, err)
	return _c
}

func (_c *MockHost_Dispatch_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, method string, data any, properties actor.JobProperties) (string, error)) *MockHost_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlarm provides a mock function for the type MockHost
func (_mock *MockHost) GetAlarm(ctx context.Context, actorType string, actorID string, name string) (actor.AlarmProperties, error) {
	ret := _mock.Called(ctx, actorType, actorID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAlarm")
	}

	var r0 actor.AlarmProperties
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (actor.AlarmProperties, error)); ok {
		return returnFunc(ctx, actorType, actorID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) actor.AlarmProperties); ok {
		r0 = returnFunc(ctx, actorType, actorID, name)
	} else {
		r0 = ret.Get(0).(actor.AlarmProperties)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, actorType, actorID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_GetAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlarm'
type MockHost_GetAlarm_Call struct {
	*mock.Call
}

// GetAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - name string
func (_e *MockHost_Expecter) GetAlarm(ctx any, actorType any, actorID any, name any) *MockHost_GetAlarm_Call {
	return &MockHost_GetAlarm_Call{Call: _e.mock.On("GetAlarm", ctx, actorType, actorID, name)}
}

func (_c *MockHost_GetAlarm_Call) Run(run func(ctx context.Context, actorType string, actorID string, name string)) *MockHost_GetAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHost_GetAlarm_Call) Return(alarmProperties actor.AlarmProperties, err error) *MockHost_GetAlarm_Call {
	_c.Call.Return(alarmProperties, err)
	return _c
}

func (_c *MockHost_GetAlarm_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, name string) (actor.AlarmProperties, error)) *MockHost_GetAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// GetJob provides a mock function for the type MockHost
func (_mock *MockHost) GetJob(ctx context.Context, jobID string) (actor.JobInfo, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 actor.JobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (actor.JobInfo, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) actor.JobInfo); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(actor.JobInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockHost_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockHost_Expecter) GetJob(ctx any, jobID any) *MockHost_GetJob_Call {
	return &MockHost_GetJob_Call{Call: _e.mock.On("GetJob", ctx, jobID)}
}

func (_c *MockHost_GetJob_Call) Run(run func(ctx context.Context, jobID string)) *MockHost_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHost_GetJob_Call) Return(jobInfo actor.JobInfo, err error) *MockHost_GetJob_Call {
	_c.Call.Return(jobInfo, err)
	return _c
}

func (_c *MockHost_GetJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) (actor.JobInfo, error)) *MockHost_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockHost
func (_mock *MockHost) GetState(ctx context.Context, actorType string, actorID string, dest any) error {
	ret := _mock.Called(ctx, actorType, actorID, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockHost_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - dest any
func (_e *MockHost_Expecter) GetState(ctx any, actorType any, actorID any, dest any) *MockHost_GetState_Call {
	return &MockHost_GetState_Call{Call: _e.mock.On("GetState", ctx, actorType, actorID, dest)}
}

func (_c *MockHost_GetState_Call) Run(run func(ctx context.Context, actorType string, actorID string, dest any)) *MockHost_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHost_GetState_Call) Return(err error) *MockHost_GetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_GetState_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, dest any) error) *MockHost_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// Halt provides a mock function for the type MockHost
func (_mock *MockHost) Halt(actorType string, actorID string) error {
	ret := _mock.Called(actorType, actorID)

	if len(ret) == 0 {
		panic("no return value specified for Halt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(actorType, actorID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_Halt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Halt'
type MockHost_Halt_Call struct {
	*mock.Call
}

// Halt is a helper method to define mock.On call
//   - actorType string
//   - actorID string
func (_e *MockHost_Expecter) Halt(actorType any, actorID any) *MockHost_Halt_Call {
	return &MockHost_Halt_Call{Call: _e.mock.On("Halt", actorType, actorID)}
}

func (_c *MockHost_Halt_Call) Run(run func(actorType string, actorID string)) *MockHost_Halt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHost_Halt_Call) Return(err error) *MockHost_Halt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_Halt_Call) RunAndReturn(run func(actorType string, actorID string) error) *MockHost_Halt_Call {
	_c.Call.Return(run)
	return _c
}

// HaltAll provides a mock function for the type MockHost
func (_mock *MockHost) HaltAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HaltAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_HaltAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HaltAll'
type MockHost_HaltAll_Call struct {
	*mock.Call
}

// HaltAll is a helper method to define mock.On call
func (_e *MockHost_Expecter) HaltAll() *MockHost_HaltAll_Call {
	return &MockHost_HaltAll_Call{Call: _e.mock.On("HaltAll")}
}

func (_c *MockHost_HaltAll_Call) Run(run func()) *MockHost_HaltAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHost_HaltAll_Call) Return(err error) *MockHost_HaltAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_HaltAll_Call) RunAndReturn(run func() error) *MockHost_HaltAll_Call {
	_c.Call.Return(run)
	return _c
}

// HaltDeferred provides a mock function for the type MockHost
func (_mock *MockHost) HaltDeferred(actorType string, actorID string) {
	_mock.Called(actorType, actorID)
	return
}

// MockHost_HaltDeferred_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HaltDeferred'
type MockHost_HaltDeferred_Call struct {
	*mock.Call
}

// HaltDeferred is a helper method to define mock.On call
//   - actorType string
//   - actorID string
func (_e *MockHost_Expecter) HaltDeferred(actorType any, actorID any) *MockHost_HaltDeferred_Call {
	return &MockHost_HaltDeferred_Call{Call: _e.mock.On("HaltDeferred", actorType, actorID)}
}

func (_c *MockHost_HaltDeferred_Call) Run(run func(actorType string, actorID string)) *MockHost_HaltDeferred_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHost_HaltDeferred_Call) Return() *MockHost_HaltDeferred_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHost_HaltDeferred_Call) RunAndReturn(run func(actorType string, actorID string)) *MockHost_HaltDeferred_Call {
	_c.Run(run)
	return _c
}

// Invoke provides a mock function for the type MockHost
func (_mock *MockHost) Invoke(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption) (actor.Envelope, error) {
	// actor.InvokeOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, actorType, actorID, method, data)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 actor.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, ...actor.InvokeOption) (actor.Envelope, error)); ok {
		return returnFunc(ctx, actorType, actorID, method, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, ...actor.InvokeOption) actor.Envelope); ok {
		r0 = returnFunc(ctx, actorType, actorID, method, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(actor.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, any, ...actor.InvokeOption) error); ok {
		r1 = returnFunc(ctx, actorType, actorID, method, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type MockHost_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - method string
//   - data any
//   - opts ...actor.InvokeOption
func (_e *MockHost_Expecter) Invoke(ctx any, actorType any, actorID any, method any, data any, opts ...any) *MockHost_Invoke_Call {
	return &MockHost_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]any{ctx, actorType, actorID, method, data}, opts...)...)}
}

func (_c *MockHost_Invoke_Call) Run(run func(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption)) *MockHost_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 []actor.InvokeOption
		variadicArgs := make([]actor.InvokeOption, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(actor.InvokeOption)
			}
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockHost_Invoke_Call) Return(envelope actor.Envelope, err error) *MockHost_Invoke_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockHost_Invoke_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption) (actor.Envelope, error)) *MockHost_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeStream provides a mock function for the type MockHost
func (_mock *MockHost) InvokeStream(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption) (string, io.ReadCloser, error) {
	// actor.InvokeOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, actorType, actorID, method, reqContentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InvokeStream")
	}

	var r0 string
	var r1 io.ReadCloser
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) (string, io.ReadCloser, error)); ok {
		return returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) string); ok {
		r0 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) io.ReadCloser); ok {
		r1 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) error); ok {
		r2 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHost_InvokeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeStream'
type MockHost_InvokeStream_Call struct {
	*mock.Call
}

// InvokeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - method string
//   - reqContentType string
//   - body io.Reader
//   - opts ...actor.InvokeOption
func (_e *MockHost_Expecter) InvokeStream(ctx any, actorType any, actorID any, method any, reqContentType any, body any, opts ...any) *MockHost_InvokeStream_Call {
	return &MockHost_InvokeStream_Call{Call: _e.mock.On("InvokeStream",
		append([]any{ctx, actorType, actorID, method, reqContentType, body}, opts...)...)}
}

func (_c *MockHost_InvokeStream_Call) Run(run func(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption)) *MockHost_InvokeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		var arg6 []actor.InvokeOption
		variadicArgs := make([]actor.InvokeOption, len(args)-6)
		for i, a := range args[6:] {
			if a != nil {
				variadicArgs[i] = a.(actor.InvokeOption)
			}
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *MockHost_InvokeStream_Call) Return(respContentType string, resp io.ReadCloser, err error) *MockHost_InvokeStream_Call {
	_c.Call.Return(respContentType, resp, err)
	return _c
}

func (_c *MockHost_InvokeStream_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption) (string, io.ReadCloser, error)) *MockHost_InvokeStream_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobs provides a mock function for the type MockHost
func (_mock *MockHost) ListJobs(ctx context.Context, actorType string, actorID string) ([]actor.JobInfo, error) {
	ret := _mock.Called(ctx, actorType, actorID)

	if len(ret) == 0 {
		panic("no return value specified for ListJobs")
	}

	var r0 []actor.JobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]actor.JobInfo, error)); ok {
		return returnFunc(ctx, actorType, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []actor.JobInfo); ok {
		r0 = returnFunc(ctx, actorType, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]actor.JobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, actorType, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_ListJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobs'
type MockHost_ListJobs_Call struct {
	*mock.Call
}

// ListJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
func (_e *MockHost_Expecter) ListJobs(ctx any, actorType any, actorID any) *MockHost_ListJobs_Call {
	return &MockHost_ListJobs_Call{Call: _e.mock.On("ListJobs", ctx, actorType, actorID)}
}

func (_c *MockHost_ListJobs_Call) Run(run func(ctx context.Context, actorType string, actorID string)) *MockHost_ListJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHost_ListJobs_Call) Return(jobInfos []actor.JobInfo, err error) *MockHost_ListJobs_Call {
	_c.Call.Return(jobInfos, err)
	return _c
}

func (_c *MockHost_ListJobs_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string) ([]actor.JobInfo, error)) *MockHost_ListJobs_Call {
	_c.Call.Return(run)
	return _c
}

// Peek provides a mock function for the type MockHost
func (_mock *MockHost) Peek(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption) (actor.Envelope, error) {
	// actor.InvokeOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, actorType, actorID, method, data)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Peek")
	}

	var r0 actor.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, ...actor.InvokeOption) (actor.Envelope, error)); ok {
		return returnFunc(ctx, actorType, actorID, method, data, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any, ...actor.InvokeOption) actor.Envelope); ok {
		r0 = returnFunc(ctx, actorType, actorID, method, data, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(actor.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, any, ...actor.InvokeOption) error); ok {
		r1 = returnFunc(ctx, actorType, actorID, method, data, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_Peek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peek'
type MockHost_Peek_Call struct {
	*mock.Call
}

// Peek is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - method string
//   - data any
//   - opts ...actor.InvokeOption
func (_e *MockHost_Expecter) Peek(ctx any, actorType any, actorID any, method any, data any, opts ...any) *MockHost_Peek_Call {
	return &MockHost_Peek_Call{Call: _e.mock.On("Peek",
		append([]any{ctx, actorType, actorID, method, data}, opts...)...)}
}

func (_c *MockHost_Peek_Call) Run(run func(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption)) *MockHost_Peek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 []actor.InvokeOption
		variadicArgs := make([]actor.InvokeOption, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(actor.InvokeOption)
			}
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockHost_Peek_Call) Return(envelope actor.Envelope, err error) *MockHost_Peek_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockHost_Peek_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, method string, data any, opts ...actor.InvokeOption) (actor.Envelope, error)) *MockHost_Peek_Call {
	_c.Call.Return(run)
	return _c
}

// PeekStream provides a mock function for the type MockHost
func (_mock *MockHost) PeekStream(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption) (string, io.ReadCloser, error) {
	// actor.InvokeOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, actorType, actorID, method, reqContentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PeekStream")
	}

	var r0 string
	var r1 io.ReadCloser
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) (string, io.ReadCloser, error)); ok {
		return returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) string); ok {
		r0 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) io.ReadCloser); ok {
		r1 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string, io.Reader, ...actor.InvokeOption) error); ok {
		r2 = returnFunc(ctx, actorType, actorID, method, reqContentType, body, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHost_PeekStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeekStream'
type MockHost_PeekStream_Call struct {
	*mock.Call
}

// PeekStream is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - method string
//   - reqContentType string
//   - body io.Reader
//   - opts ...actor.InvokeOption
func (_e *MockHost_Expecter) PeekStream(ctx any, actorType any, actorID any, method any, reqContentType any, body any, opts ...any) *MockHost_PeekStream_Call {
	return &MockHost_PeekStream_Call{Call: _e.mock.On("PeekStream",
		append([]any{ctx, actorType, actorID, method, reqContentType, body}, opts...)...)}
}

func (_c *MockHost_PeekStream_Call) Run(run func(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption)) *MockHost_PeekStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		var arg6 []actor.InvokeOption
		variadicArgs := make([]actor.InvokeOption, len(args)-6)
		for i, a := range args[6:] {
			if a != nil {
				variadicArgs[i] = a.(actor.InvokeOption)
			}
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *MockHost_PeekStream_Call) Return(respContentType string, resp io.ReadCloser, err error) *MockHost_PeekStream_Call {
	_c.Call.Return(respContentType, resp, err)
	return _c
}

func (_c *MockHost_PeekStream_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, method string, reqContentType string, body io.Reader, opts ...actor.InvokeOption) (string, io.ReadCloser, error)) *MockHost_PeekStream_Call {
	_c.Call.Return(run)
	return _c
}

// RetryJob provides a mock function for the type MockHost
func (_mock *MockHost) RetryJob(ctx context.Context, jobID string) (string, error) {
	ret := _mock.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for RetryJob")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, jobID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, jobID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHost_RetryJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryJob'
type MockHost_RetryJob_Call struct {
	*mock.Call
}

// RetryJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockHost_Expecter) RetryJob(ctx any, jobID any) *MockHost_RetryJob_Call {
	return &MockHost_RetryJob_Call{Call: _e.mock.On("RetryJob", ctx, jobID)}
}

func (_c *MockHost_RetryJob_Call) Run(run func(ctx context.Context, jobID string)) *MockHost_RetryJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHost_RetryJob_Call) Return(newJobID string, err error) *MockHost_RetryJob_Call {
	_c.Call.Return(newJobID, err)
	return _c
}

func (_c *MockHost_RetryJob_Call) RunAndReturn(run func(ctx context.Context, jobID string) (string, error)) *MockHost_RetryJob_Call {
	_c.Call.Return(run)
	return _c
}

// SetAlarm provides a mock function for the type MockHost
func (_mock *MockHost) SetAlarm(ctx context.Context, actorType string, actorID string, name string, properties actor.AlarmProperties) error {
	ret := _mock.Called(ctx, actorType, actorID, name, properties)

	if len(ret) == 0 {
		panic("no return value specified for SetAlarm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, actor.AlarmProperties) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, name, properties)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_SetAlarm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAlarm'
type MockHost_SetAlarm_Call struct {
	*mock.Call
}

// SetAlarm is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - name string
//   - properties actor.AlarmProperties
func (_e *MockHost_Expecter) SetAlarm(ctx any, actorType any, actorID any, name any, properties any) *MockHost_SetAlarm_Call {
	return &MockHost_SetAlarm_Call{Call: _e.mock.On("SetAlarm", ctx, actorType, actorID, name, properties)}
}

func (_c *MockHost_SetAlarm_Call) Run(run func(ctx context.Context, actorType string, actorID string, name string, properties actor.AlarmProperties)) *MockHost_SetAlarm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 actor.AlarmProperties
		if args[4] != nil {
			arg4 = args[4].(actor.AlarmProperties)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHost_SetAlarm_Call) Return(err error) *MockHost_SetAlarm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_SetAlarm_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, name string, properties actor.AlarmProperties) error) *MockHost_SetAlarm_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type MockHost
func (_mock *MockHost) SetState(ctx context.Context, actorType string, actorID string, state any, opts *actor.SetStateOpts) error {
	ret := _mock.Called(ctx, actorType, actorID, state, opts)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any, *actor.SetStateOpts) error); ok {
		r0 = returnFunc(ctx, actorType, actorID, state, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHost_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockHost_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx context.Context
//   - actorType string
//   - actorID string
//   - state any
//   - opts *actor.SetStateOpts
func (_e *MockHost_Expecter) SetState(ctx any, actorType any, actorID any, state any, opts any) *MockHost_SetState_Call {
	return &MockHost_SetState_Call{Call: _e.mock.On("SetState", ctx, actorType, actorID, state, opts)}
}

func (_c *MockHost_SetState_Call) Run(run func(ctx context.Context, actorType string, actorID string, state any, opts *actor.SetStateOpts)) *MockHost_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 *actor.SetStateOpts
		if args[4] != nil {
			arg4 = args[4].(*actor.SetStateOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockHost_SetState_Call) Return(err error) *MockHost_SetState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHost_SetState_Call) RunAndReturn(run func(ctx context.Context, actorType string, actorID string, state any, opts *actor.SetStateOpts) error) *MockHost_SetState_Call {
	_c.Call.Return(run)
	return _c
}
