//go:build unit

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actor_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamResponseWriter creates a new instance of MockStreamResponseWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamResponseWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamResponseWriter {
	mock := &MockStreamResponseWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamResponseWriter is an autogenerated mock type for the StreamResponseWriter type
type MockStreamResponseWriter struct {
	mock.Mock
}

type MockStreamResponseWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamResponseWriter) EXPECT() *MockStreamResponseWriter_Expecter {
	return &MockStreamResponseWriter_Expecter{mock: &_m.Mock}
}

// SetContentType provides a mock function for the type MockStreamResponseWriter
func (_mock *MockStreamResponseWriter) SetContentType(contentType string) {
	_mock.Called(contentType)
	return
}

// MockStreamResponseWriter_SetContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContentType'
type MockStreamResponseWriter_SetContentType_Call struct {
	*mock.Call
}

// SetContentType is a helper method to define mock.On call
//   - contentType string
func (_e *MockStreamResponseWriter_Expecter) SetContentType(contentType any) *MockStreamResponseWriter_SetContentType_Call {
	return &MockStreamResponseWriter_SetContentType_Call{Call: _e.mock.On("SetContentType", contentType)}
}

func (_c *MockStreamResponseWriter_SetContentType_Call) Run(run func(contentType string)) *MockStreamResponseWriter_SetContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamResponseWriter_SetContentType_Call) Return() *MockStreamResponseWriter_SetContentType_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStreamResponseWriter_SetContentType_Call) RunAndReturn(run func(contentType string)) *MockStreamResponseWriter_SetContentType_Call {
	_c.Run(run)
	return _c
}

// Write provides a mock function for the type MockStreamResponseWriter
func (_mock *MockStreamResponseWriter) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamResponseWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockStreamResponseWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockStreamResponseWriter_Expecter) Write(p any) *MockStreamResponseWriter_Write_Call {
	return &MockStreamResponseWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockStreamResponseWriter_Write_Call) Run(run func(p []byte)) *MockStreamResponseWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamResponseWriter_Write_Call) Return(n int, err error) *MockStreamResponseWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStreamResponseWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockStreamResponseWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
